{
  "hash": "63b9d5bc88b848bf8077d26000714db5",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Lab 4: Spatial Predictive Analysis\"\nsubtitle: \"Analyzing 311 Violations\"\nauthor: \"Shubhanga Satyal\"\ndate: today\nformat: \n  html:\n    code-fold: show\n    toc: true\n    toc-location: left\n    theme: cosmo\n    embed-resources: true\nexecute:\n  warning: false\n  message: false\n---\n\n+--------------------------------------------------+\n| **Table of Contents**                            |\n+--------------------------------------------------+\n| Introduction                                     |\n+--------------------------------------------------+\n| Setting Up                                       |\n+--------------------------------------------------+\n| ANALYSIS                                         |\n+--------------------------------------------------+\n| 1.  Data Loading and Exploration                 |\n+--------------------------------------------------+\n| 2.  Visualizing Abandoned Buildings              |\n+--------------------------------------------------+\n| 3.  Burglaries                                   |\n+--------------------------------------------------+\n| 4.  Visualizing Burglaries                       |\n+--------------------------------------------------+\n| 5.  Comparing Burglaries and Abandoned Buildings |\n+--------------------------------------------------+\n| 6.  Fishnet Grid Creation                        |\n+--------------------------------------------------+\n| 7.  Fishnet Grid Gets Values                     |\n+--------------------------------------------------+\n| 8.  Spatial Features                             |\n+--------------------------------------------------+\n| 9.  Local Moran's I                              |\n+--------------------------------------------------+\n| 10. Poisson Regression                           |\n+--------------------------------------------------+\n| 11. Negative Binomial (NB) Regression            |\n+--------------------------------------------------+\n| 12. Spatial Cross Validation                     |\n+--------------------------------------------------+\n| 13. Model Evaluation                             |\n+--------------------------------------------------+\n| [Note: Written Analysis Throughout]{.underline}  |\n+--------------------------------------------------+\n\n##     Assignment Overview\n\nThis assignment showcases the use of regression analysis for spatial predictive analysis in the city of Chicago. Building on 311 service requests reporting vacant and abandoned buildings, we use this spatial feature to predict the likelihood of burglaries and then compare different models to determine which performs better in spatial prediction.\\\n\\\nThis assignment focuses on adapting example code from class, to analyze a new data-set while building spatial features for predictive modeling. The analysis also emphasizes interpreting and communicating model results clearly through maps as well.\n\n## Introduction\n\nAbandoned buildings often reflect neighborhoods that have experienced disinvestment, which can gradually make them less desirable places to live. These areas may also signal limited real estate potential, contributing to environments where financially vulnerable populations are more likely to reside. Burglaries may, therefore, be one possible outcome of such conditions. Economic vulnerability can create significant stress for individuals, and vacant or abandoned buildings may serve as visible symbols of the broader economic conditions of an area. Thus, using 311 service requests reporting vacant and abandoned buildings may be an essential move for spatial predictive analysis of burglary predictions.\n\n## Setting Up\n\nThis section shows the setup for the analysis. Here, we load all the essential libraries that will be used throughout the analysis. Additionally, we create a theme for our visuals to customize and standardize their presentation. This is essential housekeeping before beginning the analysis.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Load required packages\nlibrary(tidyverse)      # Data manipulation\nlibrary(sf)             # Spatial operations\nlibrary(here)           # Relative file paths\nlibrary(viridis)        # Color scales\nlibrary(terra)          # Raster operations (replaces 'raster')\nlibrary(spdep)          # Spatial dependence\nlibrary(FNN)            # Fast nearest neighbors\nlibrary(MASS)           # Negative binomial regression\nlibrary(patchwork)      # Plot composition (replaces grid/gridExtra)\nlibrary(knitr)          # Tables\nlibrary(kableExtra)     # Table formatting\nlibrary(classInt)       # Classification intervals\n\n\n# Spatstat for analyzing point patterns - split into sub-packages\nlibrary(spatstat.geom)    # Spatial geometries\nlibrary(spatstat.explore) # Spatial exploration/KDE\n\n# Set options\noptions(scipen = 999)  # No scientific notation\nset.seed(5080)         # Reproducibility, could be any number\n\n# Create consistent theme for visualizations\ntheme_land <- function(base_size = 11) {\n  theme_minimal(base_size = base_size) +\n    theme(\n      plot.title       = element_text(face = \"bold\", size = base_size + 1),\n      plot.subtitle    = element_text(color = \"gray30\", size = base_size - 1),\n      legend.position  = \"right\",\n      panel.grid.minor = element_blank(),\n      panel.grid.major = element_line(color = \"gray92\", linewidth = 0.3),\n      panel.border     = element_blank(),\n      axis.text        = element_blank(),\n      axis.title       = element_blank(),\n      axis.ticks       = element_blank()\n    )\n}\n\n# Set as default\ntheme_set(theme_land())\n\n\ncat(\"✓ All packages loaded successfully!\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n✓ All packages loaded successfully!\n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"✓ Working directory:\", getwd(), \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n✓ Working directory: /Users/shubhangasatyal/Desktop/GitHub/SS_PPA_REPO/labs/lab4 \n```\n\n\n:::\n:::\n\n\n## ANALYSIS\n\n### 1.  Data Loading & Exploration\n\nThis chunk loads all the raw data required for the analysis, including both the spatial boundary files and the 311 calls dataset. The spatial boundaries are pulled from Chicago’s open data portal and include police districts, police beats, and the Chicago city boundary. Police districts are later used for cross-validation, where one district is held out at a time. Police beats represent a finer geographic unit and are also loaded, although they are not used as heavily in the later stages of the analysis. The Chicago city boundary is especially important, as it is used to clip all spatial data so that any points falling outside the city are removed.\n\nThe abandoned buildings data, which comes from a local CSV file, is then read into the analysis. Rows with missing coordinates are dropped, after which the dataset is converted into a spatial object. It is then reprojected to match the coordinate system used by the other spatial layers and clipped to the Chicago city boundary. These are all presented in the projection suitable for Chicago, ESRI:102271.\n\n\n::: {.cell}\n\n```{.r .cell-code}\npoliceDistricts <- \n  st_read(\"https://data.cityofchicago.org/api/geospatial/24zt-jpfn?method=export&format=GeoJSON\") %>%\n  st_transform('ESRI:102271') %>%\n  dplyr::select(District = dist_num)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nReading layer `OGRGeoJSON' from data source \n  `https://data.cityofchicago.org/api/geospatial/24zt-jpfn?method=export&format=GeoJSON' \n  using driver `GeoJSON'\nSimple feature collection with 25 features and 2 fields\nGeometry type: MULTIPOLYGON\nDimension:     XY\nBounding box:  xmin: -87.94011 ymin: 41.64455 xmax: -87.52414 ymax: 42.02303\nGeodetic CRS:  WGS 84\n```\n\n\n:::\n\n```{.r .cell-code}\npoliceBeats <- \n  st_read(\"https://data.cityofchicago.org/api/geospatial/n9it-hstw?method=export&format=GeoJSON\") %>%\n  st_transform('ESRI:102271') %>%\n  dplyr::select(Beat = beat_num)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nReading layer `OGRGeoJSON' from data source \n  `https://data.cityofchicago.org/api/geospatial/n9it-hstw?method=export&format=GeoJSON' \n  using driver `GeoJSON'\nSimple feature collection with 277 features and 4 fields\nGeometry type: MULTIPOLYGON\nDimension:     XY\nBounding box:  xmin: -87.94011 ymin: 41.64455 xmax: -87.52414 ymax: 42.02303\nGeodetic CRS:  WGS 84\n```\n\n\n:::\n\n```{.r .cell-code}\nchicagoBoundary <- \n  st_read(\"https://raw.githubusercontent.com/urbanSpatial/Public-Policy-Analytics-Landing/master/DATA/Chapter5/chicagoBoundary.geojson\") %>%\n  st_transform('ESRI:102271')\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nReading layer `chicagoBoundary' from data source \n  `https://raw.githubusercontent.com/urbanSpatial/Public-Policy-Analytics-Landing/master/DATA/Chapter5/chicagoBoundary.geojson' \n  using driver `GeoJSON'\nSimple feature collection with 1 feature and 1 field\nGeometry type: POLYGON\nDimension:     XY\nBounding box:  xmin: -87.8367 ymin: 41.64454 xmax: -87.52414 ymax: 42.02304\nGeodetic CRS:  WGS 84\n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"✓ Loaded spatial boundaries\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n✓ Loaded spatial boundaries\n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"  - Police districts:\", nrow(policeDistricts), \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  - Police districts: 25 \n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"  - Police beats:\", nrow(policeBeats), \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  - Police beats: 277 \n```\n\n\n:::\n\n```{.r .cell-code}\nabandoned <- read.csv(here(\"labs\", \"lab4\", \"VACANTLAND.csv\"))\n\nabandoned_sf <- abandoned %>%\n  filter(!is.na(LONGITUDE), !is.na(LATITUDE)) %>%\n  st_as_sf(coords = c(\"LONGITUDE\", \"LATITUDE\"), crs = 4326) %>%\n  st_transform('ESRI:102271') %>%\n  st_intersection(chicagoBoundary)\n```\n:::\n\n\n### 2.  Visualizing Abandoned Buildings\n\nThis section explores and showcases the spatial distribution of the data, first by presenting the abandoned building sites as point data. The second visualization uses a kernel density function, which provides a heat map showing where the highest concentration of service calls is received. Together, these visualizations help contextualize the spatial pattern of abandoned building concentration across Chicago.\n\n\n::: {.cell}\n\n```{.r .cell-code}\np1 <- ggplot() + \n  geom_sf(data = chicagoBoundary, fill = \"black\", color = \"white\") +\n  geom_sf(data = abandoned_sf, color = \"pink\", size = 0.01, alpha = 0.04) +\n  labs(\n    title = \"Abandoned Buildings\",\n    subtitle = paste0(\"Chicago, n = \", nrow(abandoned_sf))\n  )\n\np2 <- ggplot() + \n  geom_sf(data = chicagoBoundary, fill = \"white\", color = \"black\") +\n  geom_density_2d_filled(\n    data = data.frame(st_coordinates(abandoned_sf)),\n    aes(X, Y),\n    alpha = 0.7,\n    bins = 8\n  ) +\n  scale_fill_viridis_d(\n    option = \"viridis\",\n    direction = +1,\n    guide = \"none\"\n  ) +\n  labs(\n    title = \"Density Surface\",\n    subtitle = \"Kernel density estimation - Abandoned Buildings\"\n  )\n\np1 + p2 + \n  plot_annotation(\n    title = \"Spatial Distribution of Abandoned Buildings in Chicago\"\n  )\n```\n\n::: {.cell-output-display}\n![](FINALOMG_files/figure-html/datavisual-1.png){width=672}\n:::\n:::\n\n\nAs can be seen from the visualization, 311 calls related to abandoned buildings and lots in Chicago are located away from the downtown area, with the heaviest concentration on the South Side and a smaller cluster on the northwestern side of the city.\n\n### 3. Burglaries\n\nAs stated earlier, burglaries are the primary outcome variable on which this analysis is built, using the existing data as training material to eventually generate a spatially contextualized prediction for the future.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nburglaries <- st_read(here(\"labs\", \"lab4\", \"burglaries.shp\")) %>%\n  st_transform('ESRI:102271')\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nReading layer `burglaries' from data source \n  `/Users/shubhangasatyal/Desktop/GitHub/SS_PPA_REPO/labs/lab4/burglaries.shp' \n  using driver `ESRI Shapefile'\nSimple feature collection with 7482 features and 22 fields\nGeometry type: POINT\nDimension:     XY\nBounding box:  xmin: 340492 ymin: 552959.6 xmax: 367153.5 ymax: 594815.1\nProjected CRS: NAD83(HARN) / Illinois East\n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"\\n✓ Loaded burglary data\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n✓ Loaded burglary data\n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"  - Number of burglaries:\", nrow(burglaries), \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  - Number of burglaries: 7482 \n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"  - CRS:\", st_crs(burglaries)$input, \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  - CRS: ESRI:102271 \n```\n\n\n:::\n:::\n\n\n### 4. Visualizing Burglaries\n\nAgain, as mentioned earlier, this visualization compares the kernel density heat map with the point distribution of burglaries. This is essential for exploratory purposes, as it helps visualize and better understand the spatial distribution of burglaries.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n#burglary poit\nz1 <- ggplot() + \n  geom_sf(data = chicagoBoundary, fill = \"black\", color = \"white\") +\n  geom_sf(data = burglaries, color = \"pink\", size = 0.01, alpha = 0.4) +\n  labs(\n    title = \"Burglary Locations\",\n    subtitle = paste0(\"Chicago 2017, n = \", nrow(burglaries))\n  )\n\n#burglary heat map\nz2 <- ggplot() + \n  geom_sf(data = chicagoBoundary, fill = \"white\", color = \"black\") +\n  geom_density_2d_filled(\n    data = data.frame(st_coordinates(burglaries)),\n    aes(X, Y),\n    alpha = 0.7,\n    bins = 8\n  ) +\n  scale_fill_viridis_d(\n    option = \"viridis\",\n    direction = +1,\n    guide = \"none\"\n  ) +\n  labs(\n    title = \"Density Surface\",\n    subtitle = \"Kernel density estimation - Burglaries\"\n  )\n\nz1 + z2 + \n  plot_annotation(\n    title = \"Spatial Distribution of Burglaries in Chicago\"\n  )\n```\n\n::: {.cell-output-display}\n![](FINALOMG_files/figure-html/visualize-points-1.png){width=960}\n:::\n:::\n\n\n### 5. Comparing Burglaries and Abandoned Buildings\n\nBelow, we compare burglaries and abandoned buildings to identify visible spatial patterns. As can be seen, there is some overlap between burglaries and abandoned buildings in the southern and northwestern parts of Chicago.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nz2 + p2 +\n  plot_annotation(\n    title = \"Are Burglaries and Abandoned Buildings Correlated?\"\n  )\n```\n\n::: {.cell-output-display}\n![](FINALOMG_files/figure-html/two-map-1.png){width=672}\n:::\n:::\n\n\n### 6. Fishnet Grid Creation\n\nThe code chunk below works on creating a fishnet grid of 500m X 500m size. Fishnet grids are essential for data visualization and analysis as they are able to provide granular analyses, avoiding the bias of political boundaries. Sometimes there is variation within a larger political boundary such as a census tract or even a block group, therefore, fishnet grids help with that. Here, each cell gets a unique ID so that later you can join burglary counts and abandoned building counts onto it, essentially turning the whole city into a structured grid where every square has its own set of values to model.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n#creating grid over chicago boundaries\nfishnet <- st_make_grid(\n  chicagoBoundary,\n  cellsize = 500,\n  square = TRUE\n) %>%\n  st_sf() %>%\n  mutate(uniqueID = row_number()) %>%\n  st_transform('ESRI:102271')\n\n#fixing to only be over the city boundary\nfishnet <- fishnet[chicagoBoundary, ]\n\n#using fishnet cells to attach to districts and getting rid of those that do not fit the category. This may be neeeded in cross validation later. \nfishnet <- st_join(fishnet, policeDistricts, join = st_intersects) %>%\n  filter(!is.na(District))\n\ncat(\"✓ Created fishnet grid\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n✓ Created fishnet grid\n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"  - Number of cells:\", nrow(fishnet), \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  - Number of cells: 2891 \n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"  - Cell size: 500 x 500 meters\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  - Cell size: 500 x 500 meters\n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"  - Cell area:\", round(st_area(fishnet[1,])), \"square meters\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  - Cell area: 250000 square meters\n```\n\n\n:::\n:::\n\n\n### 7. Fishnet Grid gets Values\n\nHere, we conduct an essential analysis by first creating a kernel density estimation and assigning each cell its estimated value. This forms the basis for later model comparison. Following this, we also assign each cell the count of burglaries and the count of abandoned buildings, which may later serve as our predictors and the outcome we aim to predict, respectively. This is essential for later regression modeling.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Convert burglary points to a point pattern object (ppp) \nburglaries_ppp <- as.ppp(\n  st_coordinates(burglaries),\n  W = as.owin(st_bbox(chicagoBoundary))\n)\n\n#using kernel density estimation - one of our models of comparison\nkde_burglaries <- density.ppp(\n  burglaries_ppp,\n  sigma = 1000,\n  edge = TRUE\n)\n\n#kernel density output becomes raster and gets converted to right projection\nkde_burgraster <- rast(kde_burglaries)\ncrs(kde_burgraster) <- \"ESRI:102271\"\n\n#now, we understand the KDE for each fishnet cell here. \nfishnet <- fishnet %>%\n  mutate(\n    kde_value = terra::extract(\n      kde_burgraster,\n      vect(fishnet),\n      fun = mean,\n      na.rm = TRUE\n    )[, 2]\n  )\n\ncat(\"✓ Calculated KDE baseline\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n✓ Calculated KDE baseline\n```\n\n\n:::\n\n```{.r .cell-code}\n#counting abandoned buildings per fishnet cell\nabandoned_fishnet <- st_join(abandoned_sf, fishnet, join = st_within) %>%\n  st_drop_geometry() %>%\n  group_by(uniqueID) %>%\n  summarize(countAbandoned = n())\n\n#joining abandoned buildings back to fishnet cells\nfishnet <- fishnet %>%\n  left_join(abandoned_fishnet, by = \"uniqueID\") %>%\n  mutate(countAbandoned = replace_na(countAbandoned, 0))\n\n\n#burglary count per cell\nburglary_fishnet <- st_join(burglaries, fishnet, join = st_within) %>%\n  st_drop_geometry() %>%\n  group_by(uniqueID) %>%\n  summarize(countBurglaries = n())\n\n#same as above but for burglary \nfishnet <- fishnet %>%\n  left_join(burglary_fishnet, by = \"uniqueID\") %>%\n  mutate(countBurglaries = replace_na(countBurglaries, 0))\n\ncat(\"Abandoned building distribution:\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nAbandoned building distribution:\n```\n\n\n:::\n\n```{.r .cell-code}\nsummary(fishnet$countAbandoned)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n   Min. 1st Qu.  Median    Mean 3rd Qu.    Max. \n   0.00    1.00    9.00   35.87   37.00  448.00 \n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"Burglary count distribution:\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nBurglary count distribution:\n```\n\n\n:::\n\n```{.r .cell-code}\nsummary(fishnet$countBurglaries)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n   Min. 1st Qu.  Median    Mean 3rd Qu.    Max. \n  0.000   0.000   2.000   4.064   6.000  40.000 \n```\n\n\n:::\n:::\n\n\nLike before, we will be visualizing but in the fishnet grids to see whether there is any comparability between the counts for burglaries and abandoned buildings, and as observed earlier, there seems to be some overlap.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ny1 <- ggplot() +\n  geom_sf(data = fishnet, aes(fill = countAbandoned), color = NA) +\n  scale_fill_viridis_c(name = \"Count\", option = \"magma\") +\n  labs(title = \"Abandoned Buildings 311 Calls\") +\n  theme_land()\n\ny2 <- ggplot() +\n  geom_sf(data = fishnet, aes(fill = countBurglaries), color = NA) +\n  scale_fill_viridis_c(name = \"Count\", option = \"plasma\") +\n  labs(title = \"Burglaries\") +\n  theme_land()\n\ny1 + y2 +\n  plot_annotation(title = \"Are Abandoned Buildings and Burglaries Correlated?\")\n```\n\n::: {.cell-output-display}\n![](FINALOMG_files/figure-html/count-distri-1.png){width=672}\n:::\n:::\n\n\n### 8. Spatial Features\n\nIn this step, we calculate the k-nearest neighbors value, where k = 5, meaning the five nearest neighbors, and then find the average distance to those five nearest neighbors. This average distance will later serve as a predictor in our analysis. Here, we experiment with both 5 nearest neighbors and a second feature using 7 nearest neighbors. We find that kNN with 5 neighbors is the better predictor, based on the summary showing shorter mean and median distances, which provides a better indication of the influence of proximity.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Extract centroid coordinates of fishnet cells and point coordinates of abandoned building locations\nfishnet_coords  <- st_coordinates(st_centroid(fishnet))\nabandoned_coords <- st_coordinates(abandoned_sf)\n\n# Find the 5 nearest abandoned building points for each fishnet cell\nnn_result <- get.knnx(abandoned_coords, fishnet_coords, k = 5)\n\n#second k nearest calculation to see model predictability\nnn_result2 <- get.knnx(abandoned_coords, fishnet_coords, k = 7)\n\n#assign back to fishnet \nfishnet <- fishnet %>%\n  mutate(\n    abandoned.nn = rowMeans(nn_result$nn.dist)\n  )\n\n#assign back to fishnet\nfishnet <- fishnet %>%\n  mutate(\n    abandoned7.nn = rowMeans(nn_result2$nn.dist)\n  )\n\ncat(\"✓ 5, Calculated nearest neighbor distances\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n✓ 5, Calculated nearest neighbor distances\n```\n\n\n:::\n\n```{.r .cell-code}\nsummary(fishnet$abandoned.nn)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n     Min.   1st Qu.    Median      Mean   3rd Qu.      Max. \n   0.8906   92.5243  179.6673  290.2258  356.7141 2054.8597 \n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"✓ 7, Calculated nearest neighbor distances\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n✓ 7, Calculated nearest neighbor distances\n```\n\n\n:::\n\n```{.r .cell-code}\nsummary(fishnet$abandoned7.nn)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n    Min.  1st Qu.   Median     Mean  3rd Qu.     Max. \n   1.706  104.928  201.897  314.610  386.281 2138.988 \n```\n\n\n:::\n:::\n\n\n### 9. Local Moran's I\n\nGlobal Moran’s I helps determine whether an entire data-set within a given geography shows statistical evidence of spatial autocorrelation. Local Moran’s I does the same, but for local clusters within the bigger data-set. It helps identify where spatial autocorrelation exists. A high-high cluster means a high-value neighbor is surrounded by other high-value neighbors, while the opposite, low-low, means low-value neighbors are surrounded by other low-value neighbors. In this step, we code the Local Moran’s I for our fishnet.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n#calculating moran's i for 5 nearest neighbors (this is creating the formula)\ncalculate_local_morans <- function(data, variable, k = 5) {\n  \n  coords    <- st_coordinates(st_centroid(data))\n  neighbors <- knn2nb(knearneigh(coords, k = k))\n  weights   <- nb2listw(neighbors, style = \"W\", zero.policy = TRUE)\n  \n  x <- as.numeric(data[[variable]])\n  \n  local_moran <- localmoran(x, weights)\n  \n  mean_val <- mean(x, na.rm = TRUE)\n  \n  data %>%\n    mutate(\n      local_i      = local_moran[, 1],\n      p_value      = local_moran[, 5],\n      is_significant = p_value < 0.05,\n      moran_class  = case_when(\n        !is_significant ~ \"Not Significant\",\n        local_i > 0 & .data[[variable]] > mean_val  ~ \"High-High\",\n        local_i > 0 & .data[[variable]] <= mean_val ~ \"Low-Low\",\n        local_i < 0 & .data[[variable]] > mean_val  ~ \"High-Low\",\n        local_i < 0 & .data[[variable]] <= mean_val ~ \"Low-High\",\n        TRUE ~ \"Not Significant\"\n      )\n    )\n}\n\n\n#applying the created formula to our context for abandoned land \nfishnet <- calculate_local_morans(fishnet, \"countAbandoned\", k = 5)\n```\n:::\n\n\nWe calculate this to see where abandoned buildings cluster and where high-high clusters exist, so we can identify hotspots that can then be used to better understand burglary patterns. It is evident that only high values of abandonment surrounded by other high values will be of strong statistical interest here. A low-low cluster would not make much sense in this context, since we are looking for abandoned buildings and most buildings, in general, are occupied. Abandonment is a special occurrence and is therefore of high interest. However, we can also observe low-high patterns, where pockets of occupied fishnet cells are surrounded by areas with high abandonment. These will be displayed in the map below.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n#plotting the moran's I\nggplot() +\n  geom_sf(\n    data = fishnet,\n    aes(fill = moran_class),\n    color = NA\n  ) +\n  scale_fill_manual(\n    values = c(\n      \"High-High\"       = \"#d7191c\",\n      \"High-Low\"        = \"#fdae61\",\n      \"Low-High\"        = \"#abd9e9\",\n      \"Low-Low\"         = \"#2c7bb6\",\n      \"Not Significant\" = \"gray90\"\n    ),\n    name = \"Cluster Type\"\n  ) +\n  labs(\n    title    = \"Local Moran's I: Vacant Building Clusters\",\n    subtitle = \"High-High = Hot spots of disorder\"\n  ) +\n  theme_land()\n```\n\n::: {.cell-output-display}\n![](FINALOMG_files/figure-html/hotspot-1.png){width=768}\n:::\n:::\n\n\nNow, we conduct another spatial feature engineering step. Here, we calculate the distance from hotspots to the center of each fishnet cell and then use the count of burglaries, perhaps along with distance, as a predictor. This will help us determine whether proximity to a hotspot may be associated with burglaries.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n#centroid of hotspot\nhotspots <- fishnet %>%\n  filter(moran_class == \"High-High\") %>%\n  st_centroid()\n\n# Calculate each cell's distance to the nearest abandoned building hot spot cluster\n# If no hot spots exist, default to 0\nif (nrow(hotspots) > 0) {\n  fishnet <- fishnet %>%\n    mutate(\n      dist_to_hotspot = as.numeric(\n        st_distance(st_centroid(fishnet), hotspots %>% st_union())\n      )\n    )\n  cat(\"✓ Calculated distance to vacant building hot spots\\n\")\n  cat(\"  - Number of hot spot cells:\", nrow(hotspots), \"\\n\")\n} else {\n  fishnet <- fishnet %>%\n    mutate(dist_to_hotspot = 0)\n  cat(\"⚠ No significant hot spots found\\n\")\n}\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n✓ Calculated distance to vacant building hot spots\n  - Number of hot spot cells: 395 \n```\n\n\n:::\n:::\n\n\n### 10. Poisson Regression\n\nSince there is a high likelihood of skewness, we use Poisson regression here. Many fishnet grids may have a value of 0; therefore, Poisson regression becomes our choice instead of a normal regression.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Strip geometry and keep only the variables needed for modeling,\n# then drop any rows with missing values so the regression runs cleanly\nfishnet_model <- fishnet %>%\n  st_drop_geometry() %>%\n  dplyr::select(\n    uniqueID,\n    District,\n    countBurglaries,\n    countAbandoned,\n    abandoned.nn,\n    dist_to_hotspot\n  ) %>%\n  na.omit()\n\ncat(\"✓ Prepared modeling data\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n✓ Prepared modeling data\n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"  - Observations:\", nrow(fishnet_model), \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  - Observations: 2891 \n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"  - Variables:\",    ncol(fishnet_model), \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  - Variables: 6 \n```\n\n\n:::\n\n```{.r .cell-code}\n# Fit a Poisson regression model predicting burglary counts\nset.seed(5080)\nmodel_poisson <- glm(\n  countBurglaries ~ countAbandoned + abandoned.nn + dist_to_hotspot,\n  data   = fishnet_model,\n  family = \"poisson\"\n)\n\nsummary(model_poisson)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nglm(formula = countBurglaries ~ countAbandoned + abandoned.nn + \n    dist_to_hotspot, family = \"poisson\", data = fishnet_model)\n\nCoefficients:\n                    Estimate   Std. Error z value             Pr(>|z|)    \n(Intercept)      2.026450582  0.022614048  89.610 < 0.0000000000000002 ***\ncountAbandoned   0.002788315  0.000124876  22.329 < 0.0000000000000002 ***\nabandoned.nn    -0.003900210  0.000102362 -38.102 < 0.0000000000000002 ***\ndist_to_hotspot -0.000031874  0.000005519  -5.776        0.00000000766 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\n(Dispersion parameter for poisson family taken to be 1)\n\n    Null deviance: 17012.3  on 2890  degrees of freedom\nResidual deviance:  9852.1  on 2887  degrees of freedom\nAIC: 16412\n\nNumber of Fisher Scoring iterations: 6\n```\n\n\n:::\n:::\n\n\nAll three predictors are highly significant, with p-values below 0.001. countAbandoned has a positive coefficient, suggesting that as the number of abandoned buildings in a cell increases, the expected count of burglaries also increases. abandoned.nn has a negative coefficient, meaning that as the distance from abandoned buildings increases, the expected number of burglaries decreases. Similarly, dist_to_hotspot is also negative, suggesting that cells located farther from hotspot clusters tend to have fewer burglaries.\n\n### 11. Negative Binomial Regression\n\nWe check for the dispersion parameter fir the Poisson distriibution first, and if it is over 1.5, we fit the negative binomial regression. Sticking to Poisson despite dispersion can lead to underestimation, leading to inaccurate interpretation. Here, we do observe dispersion therefore, switch to Negative Binomial Regression.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndispersion <- sum(residuals(model_poisson, type = \"pearson\")^2) /\n              model_poisson$df.residual\n\ncat(\"Dispersion parameter:\", round(dispersion, 2), \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nDispersion parameter: 4.16 \n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"Rule of thumb: >1.5 suggests overdispersion\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nRule of thumb: >1.5 suggests overdispersion\n```\n\n\n:::\n\n```{.r .cell-code}\nif (dispersion > 1.5) {\n  cat(\"⚠ Overdispersion detected! Consider Negative Binomial model.\\n\")\n} else {\n  cat(\"✓ Dispersion looks okay for Poisson model.\\n\")\n}\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n⚠ Overdispersion detected! Consider Negative Binomial model.\n```\n\n\n:::\n:::\n\n\ndist_to_hotspot is not statistically significant, so distance from the nearest hotspot does not seem to meaningfully predict burglaries in this model.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n#fitting the nb model\nset.seed(5080)\nmodel_nb <- glm.nb(\n  countBurglaries ~ countAbandoned + abandoned.nn + dist_to_hotspot,\n  data = fishnet_model\n)\n\nsummary(model_nb)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nglm.nb(formula = countBurglaries ~ countAbandoned + abandoned.nn + \n    dist_to_hotspot, data = fishnet_model, init.theta = 1.384859966, \n    link = log)\n\nCoefficients:\n                    Estimate   Std. Error z value            Pr(>|z|)    \n(Intercept)      2.034262377  0.048825329  41.664 <0.0000000000000002 ***\ncountAbandoned   0.003319996  0.000348747   9.520 <0.0000000000000002 ***\nabandoned.nn    -0.004530591  0.000166143 -27.269 <0.0000000000000002 ***\ndist_to_hotspot -0.000005053  0.000010172  -0.497               0.619    \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\n(Dispersion parameter for Negative Binomial(1.3849) family taken to be 1)\n\n    Null deviance: 5334.3  on 2890  degrees of freedom\nResidual deviance: 3050.7  on 2887  degrees of freedom\nAIC: 12646\n\nNumber of Fisher Scoring iterations: 1\n\n              Theta:  1.3849 \n          Std. Err.:  0.0593 \n\n 2 x log-likelihood:  -12636.3750 \n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"\\nModel Comparison:\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nModel Comparison:\n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"Poisson AIC:\",           round(AIC(model_poisson), 1), \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nPoisson AIC: 16411.8 \n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"Negative Binomial AIC:\", round(AIC(model_nb),      1), \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nNegative Binomial AIC: 12646.4 \n```\n\n\n:::\n:::\n\n\nBetween the two models, Negative Binomial is a better fit because, it has lower AIC of 12646.4 vs Poisson which has 16411.8. Lower the AIC the better.\n\n### 12. Spatial Cross-Validation\n\nWe hold one district out at a time, fit the model on the rest, and then predict for that held-out district. This process is repeated until every district has served as the test set once, helping us understand how well the model generalizes to completely new spatial areas. We use the Leave-One-Group-Out cross validation, by holding out entire police districts at a time, we ensure that the test area is truly spatially separated from the training data. This gives a more honest picture of how the model would perform when applied to a new area it has not seen before. We then calculate the Mean Absolute Error and the Root Mean Square Error. These are tests for the predictive accuracy of the model. Lower the RMSE the better the model predictions.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndistricts  <- unique(fishnet_model$District)\ncv_results <- tibble()\n\ncat(\"Running LOGO Cross-Validation...\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nRunning LOGO Cross-Validation...\n```\n\n\n:::\n\n```{.r .cell-code}\n#the cross validatyion model \nfor (i in seq_along(districts)) {\n  \n  test_district <- districts[i]\n  \n  train_data <- fishnet_model %>% filter(District != test_district)\n  test_data  <- fishnet_model %>% filter(District == test_district)\n  \n  model_cv <- glm.nb(\n    countBurglaries ~ countAbandoned + abandoned.nn + dist_to_hotspot,\n    data = train_data\n  )\n  \n  test_data <- test_data %>%\n    mutate(prediction = predict(model_cv, test_data, type = \"response\"))\n  \n  mae  <- mean(abs(test_data$countBurglaries - test_data$prediction))\n  rmse <- sqrt(mean((test_data$countBurglaries - test_data$prediction)^2))\n  \n  cv_results <- bind_rows(\n    cv_results,\n    tibble(\n      fold          = i,\n      test_district = test_district,\n      n_test        = nrow(test_data),\n      mae           = mae,\n      rmse          = rmse\n    )\n  )\n  \n  cat(\"  Fold\", i, \"/\", length(districts), \"- District\", test_district,\n      \"- MAE:\", round(mae, 2), \"\\n\")\n}%>%\n  kable()\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  Fold 1 / 23 - District 5 - MAE: 2.75 \n  Fold 2 / 23 - District 4 - MAE: 2.1 \n  Fold 3 / 23 - District 22 - MAE: 2.85 \n  Fold 4 / 23 - District 31 - MAE: 1.18 \n  Fold 5 / 23 - District 6 - MAE: 4.03 \n  Fold 6 / 23 - District 8 - MAE: 2.19 \n  Fold 7 / 23 - District 7 - MAE: 7.47 \n  Fold 8 / 23 - District 3 - MAE: 4.74 \n  Fold 9 / 23 - District 2 - MAE: 2.67 \n  Fold 10 / 23 - District 9 - MAE: 2.99 \n  Fold 11 / 23 - District 10 - MAE: 2.65 \n  Fold 12 / 23 - District 1 - MAE: 2.83 \n  Fold 13 / 23 - District 12 - MAE: 4.22 \n  Fold 14 / 23 - District 15 - MAE: 2.75 \n  Fold 15 / 23 - District 11 - MAE: 4.65 \n  Fold 16 / 23 - District 18 - MAE: 3.02 \n  Fold 17 / 23 - District 25 - MAE: 3.49 \n  Fold 18 / 23 - District 14 - MAE: 4.41 \n  Fold 19 / 23 - District 19 - MAE: 2.05 \n  Fold 20 / 23 - District 16 - MAE: 2.02 \n  Fold 21 / 23 - District 17 - MAE: 2.29 \n  Fold 22 / 23 - District 20 - MAE: 2.29 \n  Fold 23 / 23 - District 24 - MAE: 1.87 \n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"\\n✓ Cross-Validation Complete\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n✓ Cross-Validation Complete\n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"Mean MAE:\",  round(mean(cv_results$mae),  2), \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nMean MAE: 3.11 \n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"Mean RMSE:\", round(mean(cv_results$rmse), 2), \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nMean RMSE: 4.6 \n```\n\n\n:::\n:::\n\n\nFrom the MAEs, we can understand that the high MAE of 7.47 in District (fold) 7 shows where the model struggles, whereas the MAE of 1.18 in District (fold) 4 shows that the model performs much better there. The RMSE of 4.6, being noticeably higher than the MAE of 3.11, further suggests that while the average error is moderate, there are still some cells with much larger prediction errors.\n\n### 13. Model Evaluation\n\n-   Compare to KDE baseline\n\n\n::: {.cell}\n\n```{.r .cell-code}\nset.seed(5080)\nfinal_model <- glm.nb(\n  countBurglaries ~ countAbandoned + abandoned.nn + dist_to_hotspot,\n  data = fishnet_model\n)\n\n# predict directly on fishnet_model and join back\nfishnet_model <- fishnet_model %>%\n  mutate(prediction_nb = predict(final_model, ., type = \"response\"))\n\n# drop any existing prediction_nb column from fishnet before joining\nfishnet <- fishnet %>%\n  dplyr::select(-any_of(\"prediction_nb\")) %>%\n  left_join(\n    fishnet_model %>% dplyr::select(uniqueID, prediction_nb),\n    by = \"uniqueID\"\n  )\n\n# verify it worked\ncat(\"prediction_nb missing values:\", sum(is.na(fishnet$prediction_nb)), \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nprediction_nb missing values: 0 \n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"prediction_nb range:\", round(min(fishnet$prediction_nb, na.rm=TRUE), 2), \n    \"to\", round(max(fishnet$prediction_nb, na.rm=TRUE), 2), \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nprediction_nb range: 0 to 28.11 \n```\n\n\n:::\n\n```{.r .cell-code}\n#Scale KDE values to match the total burglary count, so that KDE and the negative binomial predictions are on the same scale for fair comparison\nkde_sum   <- sum(fishnet$kde_value,       na.rm = TRUE)\ncount_sum <- sum(fishnet$countBurglaries, na.rm = TRUE)\n\nfishnet <- fishnet %>%\n  mutate(prediction_kde = (kde_value / kde_sum) * count_sum)\n\n\n#visualize burglaries actual, Negative Binomial Model, and KDE\nm1 <- ggplot() +\n  geom_sf(data = fishnet, aes(fill = countBurglaries), color = NA) +\n  scale_fill_viridis_c(name = \"Count\", option = \"plasma\", limits = c(0, 15)) +\n  labs(title = \"Actual Burglaries\") +\n  theme_land()\n\nm2 <- ggplot() +\n  geom_sf(data = fishnet, aes(fill = prediction_nb), color = NA) +\n  scale_fill_viridis_c(name = \"Predicted\", option = \"plasma\", limits = c(0, 15)) +\n  labs(title = \"Model Predictions (NB)\") +\n  theme_land()\n\nm3 <- ggplot() +\n  geom_sf(data = fishnet, aes(fill = prediction_kde), color = NA) +\n  scale_fill_viridis_c(name = \"Predicted\", option = \"plasma\", limits = c(0, 15)) +\n  labs(title = \"KDE Baseline Predictions\") +\n  theme_land()\n\nm1 + m2 + m3 +\n  plot_annotation(\n    title    = \"Actual vs. Predicted Burglaries\",\n    subtitle = \"Does our complex model outperform simple KDE?\"\n  )\n```\n\n::: {.cell-output-display}\n![](FINALOMG_files/figure-html/model-comparison-1.png){width=672}\n:::\n:::\n\n\nVisually, all three look similar, therefore a more robust comparison is required.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncomparison <- fishnet %>%\n  st_drop_geometry() %>%\n  filter(!is.na(prediction_nb), !is.na(prediction_kde)) %>%\n  summarize(\n    model_mae  = mean(abs(countBurglaries - prediction_nb)),\n    model_rmse = sqrt(mean((countBurglaries - prediction_nb)^2)),\n    kde_mae    = mean(abs(countBurglaries - prediction_kde)),\n    kde_rmse   = sqrt(mean((countBurglaries - prediction_kde)^2))\n  )\n\ncomparison %>%\n  pivot_longer(everything(), names_to = \"metric\", values_to = \"value\") %>%\n  separate(metric, into = c(\"approach\", \"metric\"), sep = \"_\") %>%\n  pivot_wider(names_from = metric, values_from = value) %>%\n  kable(\n    digits  = 2,\n    caption = \"Model Performance Comparison\"\n  ) %>%\n  kable_styling(bootstrap_options = c(\"striped\", \"hover\"))\n```\n\n::: {.cell-output-display}\n`````{=html}\n<table class=\"table table-striped table-hover\" style=\"margin-left: auto; margin-right: auto;\">\n<caption>Model Performance Comparison</caption>\n <thead>\n  <tr>\n   <th style=\"text-align:left;\"> approach </th>\n   <th style=\"text-align:right;\"> mae </th>\n   <th style=\"text-align:right;\"> rmse </th>\n  </tr>\n </thead>\n<tbody>\n  <tr>\n   <td style=\"text-align:left;\"> model </td>\n   <td style=\"text-align:right;\"> 3.25 </td>\n   <td style=\"text-align:right;\"> 5.21 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> kde </td>\n   <td style=\"text-align:right;\"> 3.29 </td>\n   <td style=\"text-align:right;\"> 5.00 </td>\n  </tr>\n</tbody>\n</table>\n\n`````\n:::\n:::\n\n\nTo conclude, we can see that the KDE performs better than the model itself, with lower MAE and RMSE values. While the Negative Binomial regression is technically more robust, the possibility of missing spatial variables beyond those included in the model may be one reason for this weaker performance.\n\n#### ACKNOWLEDGMENT\n\n\\\nI have leveraged the in-class exercise provided by professor Lassiter for the code. I also leveraged AI for debugging, explaining new codes functionality whenever I was stuck while producing this lab content.\n\n------------------------------------------------------------------------\n",
    "supporting": [
      "FINALOMG_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {
      "include-in-header": [
        "<script src=\"../../site_libs/kePrint-0.0.1/kePrint.js\"></script>\n<link href=\"../../site_libs/lightable-0.0.1/lightable.css\" rel=\"stylesheet\" />\n"
      ]
    },
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}