<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.8.27">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Shubhanga Satyal">
<meta name="dcterms.date" content="2026-02-10">

<title>Lab 1: Census Data Quality for Policy Decisions – Shubhanga Satyal-MUSA 5080 Portfolio</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="../../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../../site_libs/clipboard/clipboard.min.js"></script>
<script src="../../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../../site_libs/quarto-search/fuse.min.js"></script>
<script src="../../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../../">
<script src="../../site_libs/quarto-html/quarto.js" type="module"></script>
<script src="../../site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="../../site_libs/quarto-html/axe/axe-check.js" type="module"></script>
<script src="../../site_libs/quarto-html/popper.min.js"></script>
<script src="../../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../../site_libs/quarto-html/anchor.min.js"></script>
<link href="../../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../../site_libs/quarto-html/quarto-syntax-highlighting-ed96de9b727972fe78a7b5d16c58bf87.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../../site_libs/bootstrap/bootstrap-5b4ad623e5705c0698d39aec6f10cf02.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>


</head>

<body class="floating nav-fixed quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a class="navbar-brand" href="../../index.html">
    <span class="navbar-title">Shubhanga Satyal-MUSA 5080 Portfolio</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" role="menu" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item">
    <a class="nav-link" href="../../index.html"> 
<span class="menu-text">Home</span></a>
  </li>  
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-labs" role="link" data-bs-toggle="dropdown" aria-expanded="false">
 <span class="menu-text">labs</span>
    </a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-labs">    
        <li>
    <a class="dropdown-item" href="../../labs/lab0/lab0_template.html">
 <span class="dropdown-text">Lab 0: dplyr Basic</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../labs/lab1/lab1_template.html">
 <span class="dropdown-text">Lab 1: Census Data Quality for Policy Decisions</span></a>
  </li>  
    </ul>
  </li>
</ul>
          </div> <!-- /navcollapse -->
            <div class="quarto-navbar-tools">
</div>
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation floating overflow-auto">
    <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#assignment-overview" id="toc-assignment-overview" class="nav-link active" data-scroll-target="#assignment-overview">Assignment Overview</a>
  <ul class="collapse">
  <li><a href="#scenario" id="toc-scenario" class="nav-link" data-scroll-target="#scenario">Scenario</a></li>
  <li><a href="#learning-objectives" id="toc-learning-objectives" class="nav-link" data-scroll-target="#learning-objectives">Learning Objectives</a></li>
  <li><a href="#submission-instructions" id="toc-submission-instructions" class="nav-link" data-scroll-target="#submission-instructions">Submission Instructions</a></li>
  </ul></li>
  <li><a href="#part-1-portfolio-integration" id="toc-part-1-portfolio-integration" class="nav-link" data-scroll-target="#part-1-portfolio-integration">Part 1: Portfolio Integration</a></li>
  <li><a href="#setup" id="toc-setup" class="nav-link" data-scroll-target="#setup">Setup</a></li>
  <li><a href="#part-2-county-level-resource-assessment" id="toc-part-2-county-level-resource-assessment" class="nav-link" data-scroll-target="#part-2-county-level-resource-assessment">Part 2: County-Level Resource Assessment</a>
  <ul class="collapse">
  <li><a href="#data-retrieval" id="toc-data-retrieval" class="nav-link" data-scroll-target="#data-retrieval">2.1 Data Retrieval</a></li>
  <li><a href="#data-quality-assessment" id="toc-data-quality-assessment" class="nav-link" data-scroll-target="#data-quality-assessment">2.2 Data Quality Assessment</a></li>
  <li><a href="#high-uncertainty-counties" id="toc-high-uncertainty-counties" class="nav-link" data-scroll-target="#high-uncertainty-counties">2.3 High Uncertainty Counties</a></li>
  </ul></li>
  <li><a href="#part-3-neighborhood-level-analysis" id="toc-part-3-neighborhood-level-analysis" class="nav-link" data-scroll-target="#part-3-neighborhood-level-analysis">Part 3: Neighborhood-Level Analysis</a>
  <ul class="collapse">
  <li><a href="#focus-area-selection" id="toc-focus-area-selection" class="nav-link" data-scroll-target="#focus-area-selection">3.1 Focus Area Selection</a></li>
  <li><a href="#tract-level-demographics" id="toc-tract-level-demographics" class="nav-link" data-scroll-target="#tract-level-demographics">3.2 Tract-Level Demographics</a></li>
  <li><a href="#demographic-analysis" id="toc-demographic-analysis" class="nav-link" data-scroll-target="#demographic-analysis">3.3 Demographic Analysis</a></li>
  </ul></li>
  <li><a href="#part-4-comprehensive-data-quality-evaluation" id="toc-part-4-comprehensive-data-quality-evaluation" class="nav-link" data-scroll-target="#part-4-comprehensive-data-quality-evaluation">Part 4: Comprehensive Data Quality Evaluation</a>
  <ul class="collapse">
  <li><a href="#moe-analysis-for-demographic-variables" id="toc-moe-analysis-for-demographic-variables" class="nav-link" data-scroll-target="#moe-analysis-for-demographic-variables">4.1 MOE Analysis for Demographic Variables</a></li>
  <li><a href="#pattern-analysis" id="toc-pattern-analysis" class="nav-link" data-scroll-target="#pattern-analysis">4.2 Pattern Analysis</a></li>
  </ul></li>
  <li><a href="#part-5-policy-recommendations" id="toc-part-5-policy-recommendations" class="nav-link" data-scroll-target="#part-5-policy-recommendations">Part 5: Policy Recommendations</a>
  <ul class="collapse">
  <li><a href="#analysis-integration-and-professional-summary" id="toc-analysis-integration-and-professional-summary" class="nav-link" data-scroll-target="#analysis-integration-and-professional-summary">5.1 Analysis Integration and Professional Summary</a></li>
  <li><a href="#specific-recommendations" id="toc-specific-recommendations" class="nav-link" data-scroll-target="#specific-recommendations">6.3 Specific Recommendations</a></li>
  <li><a href="#questions-for-further-investigation" id="toc-questions-for-further-investigation" class="nav-link" data-scroll-target="#questions-for-further-investigation">Questions for Further Investigation</a></li>
  </ul></li>
  <li><a href="#technical-notes" id="toc-technical-notes" class="nav-link" data-scroll-target="#technical-notes">Technical Notes</a>
  <ul class="collapse">
  <li><a href="#submission-checklist" id="toc-submission-checklist" class="nav-link" data-scroll-target="#submission-checklist">Submission Checklist</a></li>
  </ul></li>
  </ul>
</nav>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar zindex-bottom">
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Lab 1: Census Data Quality for Policy Decisions</h1>
<p class="subtitle lead">Evaluating Data Reliability for Algorithmic Decision-Making</p>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Shubhanga Satyal </p>
          </div>
  </div>
    
    <div>
    <div class="quarto-title-meta-heading">Published</div>
    <div class="quarto-title-meta-contents">
      <p class="date">February 10, 2026</p>
    </div>
  </div>
  
    
  </div>
  


</header>


<section id="assignment-overview" class="level1">
<h1>Assignment Overview</h1>
<section id="scenario" class="level2">
<h2 class="anchored" data-anchor-id="scenario">Scenario</h2>
<p>You are a data analyst for the <strong>California Department of Human Services</strong>. The department is considering implementing an algorithmic system to identify communities that should receive priority for social service funding and outreach programs. Your supervisor has asked you to evaluate the quality and reliability of available census data to inform this decision.</p>
<p>Drawing on our Week 2 discussion of algorithmic bias, you need to assess not just what the data shows, but how reliable it is and what communities might be affected by data quality issues.</p>
</section>
<section id="learning-objectives" class="level2">
<h2 class="anchored" data-anchor-id="learning-objectives">Learning Objectives</h2>
<ul>
<li>Apply dplyr functions to real census data for policy analysis</li>
<li>Evaluate data quality using margins of error</li>
<li>Connect technical analysis to algorithmic decision-making</li>
<li>Identify potential equity implications of data reliability issues</li>
<li>Create professional documentation for policy stakeholders</li>
</ul>
</section>
<section id="submission-instructions" class="level2">
<h2 class="anchored" data-anchor-id="submission-instructions">Submission Instructions</h2>
<p><strong>Submit by posting your updated portfolio link on Canvas.</strong> Your assignment should be accessible at <code>your-portfolio-url/labs/lab_1/</code></p>
<p>Make sure to update your <code>_quarto.yml</code> navigation to include this assignment under an “Labs” menu.</p>
</section>
</section>
<section id="part-1-portfolio-integration" class="level1">
<h1>Part 1: Portfolio Integration</h1>
<p>Create this assignment in your portfolio repository under an <code>labs/lab_1/</code> folder structure. Update your navigation menu to include:</p>
<pre><code>- text: Assignments
  menu:
    - href: labs/lab_1/your_file_name.qmd
      text: "Lab 1: Census Data Exploration"</code></pre>
<p>If there is a special character like a colon, you need use double quote mark so that the quarto can identify this as text</p>
</section>
<section id="setup" class="level1">
<h1>Setup</h1>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Load required packages (hint: you need tidycensus, tidyverse, and knitr)</span></span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidycensus)</span>
<span id="cb2-3"><a href="#cb2-3" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyverse)</span>
<span id="cb2-4"><a href="#cb2-4" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(knitr)</span>
<span id="cb2-5"><a href="#cb2-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-6"><a href="#cb2-6" aria-hidden="true" tabindex="-1"></a><span class="co"># Set your Census API key</span></span>
<span id="cb2-7"><a href="#cb2-7" aria-hidden="true" tabindex="-1"></a><span class="fu">census_api_key</span>(<span class="fu">Sys.getenv</span>(<span class="st">"82d6bed7434dbceef02889e5a0d354feff424c8b."</span>))</span>
<span id="cb2-8"><a href="#cb2-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-9"><a href="#cb2-9" aria-hidden="true" tabindex="-1"></a><span class="co"># Choose your state for analysis - assign it to a variable called my_state</span></span>
<span id="cb2-10"><a href="#cb2-10" aria-hidden="true" tabindex="-1"></a>my_state <span class="ot">&lt;-</span> <span class="st">"CA"</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p><strong>State Selection:</strong> I have chosen <strong>California</strong> for this analysis because: While I am not from America, California would be a state I would like to visit.</p>
</section>
<section id="part-2-county-level-resource-assessment" class="level1">
<h1>Part 2: County-Level Resource Assessment</h1>
<section id="data-retrieval" class="level2">
<h2 class="anchored" data-anchor-id="data-retrieval">2.1 Data Retrieval</h2>
<p><strong>Your Task:</strong> Use <code>get_acs()</code> to retrieve county-level data for your chosen state.</p>
<p><strong>Requirements:</strong> - Geography: county level - Variables: median household income (B19013_001) and total population (B01003_001)<br>
- Year: 2022 - Survey: acs5 - Output format: wide</p>
<p><strong>Hint:</strong> Remember to give your variables descriptive names using the <code>variables = c(name = "code")</code> syntax.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Write your get_acs() code here</span></span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a>ca_county_data <span class="ot">&lt;-</span> <span class="fu">get_acs</span>(</span>
<span id="cb3-3"><a href="#cb3-3" aria-hidden="true" tabindex="-1"></a>  <span class="at">geography =</span> <span class="st">"county"</span>,</span>
<span id="cb3-4"><a href="#cb3-4" aria-hidden="true" tabindex="-1"></a>  <span class="at">state =</span> my_state,</span>
<span id="cb3-5"><a href="#cb3-5" aria-hidden="true" tabindex="-1"></a>  <span class="at">variables =</span> <span class="fu">c</span>(</span>
<span id="cb3-6"><a href="#cb3-6" aria-hidden="true" tabindex="-1"></a>    <span class="at">median_hh_income =</span> <span class="st">"B19013_001"</span>,</span>
<span id="cb3-7"><a href="#cb3-7" aria-hidden="true" tabindex="-1"></a>    <span class="at">total_pop =</span> <span class="st">"B01003_001"</span></span>
<span id="cb3-8"><a href="#cb3-8" aria-hidden="true" tabindex="-1"></a>  ),</span>
<span id="cb3-9"><a href="#cb3-9" aria-hidden="true" tabindex="-1"></a>  <span class="at">year=</span> <span class="dv">2022</span>,</span>
<span id="cb3-10"><a href="#cb3-10" aria-hidden="true" tabindex="-1"></a>  <span class="at">survey =</span> <span class="st">"acs5"</span>,</span>
<span id="cb3-11"><a href="#cb3-11" aria-hidden="true" tabindex="-1"></a>  <span class="at">output =</span> <span class="st">"wide"</span></span>
<span id="cb3-12"><a href="#cb3-12" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb3-13"><a href="#cb3-13" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-14"><a href="#cb3-14" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(ca_county_data)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 6 × 6
  GEOID NAME           median_hh_incomeE median_hh_incomeM total_popE total_popM
  &lt;chr&gt; &lt;chr&gt;                      &lt;dbl&gt;             &lt;dbl&gt;      &lt;dbl&gt;      &lt;dbl&gt;
1 06001 Alameda Count…            122488              1231    1663823         NA
2 06003 Alpine County…            101125             17442       1515        206
3 06005 Amador County…             74853              6048      40577         NA
4 06007 Butte County,…             66085              2261     213605         NA
5 06009 Calaveras Cou…             77526              3875      45674         NA
6 06011 Colusa County…             69619              5745      21811         NA</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Clean the county names to remove state name and "County" </span></span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a><span class="co"># Hint: use mutate() with str_remove()</span></span>
<span id="cb5-3"><a href="#cb5-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-4"><a href="#cb5-4" aria-hidden="true" tabindex="-1"></a>clean_data <span class="ot">&lt;-</span> ca_county_data <span class="sc">%&gt;%</span></span>
<span id="cb5-5"><a href="#cb5-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(</span>
<span id="cb5-6"><a href="#cb5-6" aria-hidden="true" tabindex="-1"></a>    <span class="at">NAME =</span> NAME <span class="sc">%&gt;%</span></span>
<span id="cb5-7"><a href="#cb5-7" aria-hidden="true" tabindex="-1"></a>      <span class="fu">str_remove</span>(<span class="st">", California"</span>) <span class="sc">%&gt;%</span></span>
<span id="cb5-8"><a href="#cb5-8" aria-hidden="true" tabindex="-1"></a>      <span class="fu">str_remove</span>(<span class="st">" County"</span>)</span>
<span id="cb5-9"><a href="#cb5-9" aria-hidden="true" tabindex="-1"></a>  )<span class="sc">%&gt;%</span></span>
<span id="cb5-10"><a href="#cb5-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(<span class="st">`</span><span class="at">County</span><span class="st">`</span> <span class="ot">=</span> <span class="st">"NAME"</span>,</span>
<span id="cb5-11"><a href="#cb5-11" aria-hidden="true" tabindex="-1"></a>         <span class="st">`</span><span class="at">Median Household Income</span><span class="st">`</span> <span class="ot">=</span> <span class="st">"median_hh_incomeE"</span>,</span>
<span id="cb5-12"><a href="#cb5-12" aria-hidden="true" tabindex="-1"></a>         <span class="st">`</span><span class="at">Median HH Income Margin of Error</span><span class="st">`</span> <span class="ot">=</span> <span class="st">"median_hh_incomeM"</span>,</span>
<span id="cb5-13"><a href="#cb5-13" aria-hidden="true" tabindex="-1"></a>        <span class="st">`</span><span class="at">Total Population</span><span class="st">`</span> <span class="ot">=</span> <span class="st">"total_popE"</span>,</span>
<span id="cb5-14"><a href="#cb5-14" aria-hidden="true" tabindex="-1"></a>        )</span>
<span id="cb5-15"><a href="#cb5-15" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-16"><a href="#cb5-16" aria-hidden="true" tabindex="-1"></a><span class="co"># Display the first few rows</span></span>
<span id="cb5-17"><a href="#cb5-17" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(clean_data)<span class="sc">%&gt;%</span></span>
<span id="cb5-18"><a href="#cb5-18" aria-hidden="true" tabindex="-1"></a>  <span class="fu">kable</span>()</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<colgroup>
<col style="width: 11%">
<col style="width: 28%">
<col style="width: 39%">
<col style="width: 20%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">County</th>
<th style="text-align: right;">Median Household Income</th>
<th style="text-align: right;">Median HH Income Margin of Error</th>
<th style="text-align: right;">Total Population</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Alameda</td>
<td style="text-align: right;">122488</td>
<td style="text-align: right;">1231</td>
<td style="text-align: right;">1663823</td>
</tr>
<tr class="even">
<td style="text-align: left;">Alpine</td>
<td style="text-align: right;">101125</td>
<td style="text-align: right;">17442</td>
<td style="text-align: right;">1515</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Amador</td>
<td style="text-align: right;">74853</td>
<td style="text-align: right;">6048</td>
<td style="text-align: right;">40577</td>
</tr>
<tr class="even">
<td style="text-align: left;">Butte</td>
<td style="text-align: right;">66085</td>
<td style="text-align: right;">2261</td>
<td style="text-align: right;">213605</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Calaveras</td>
<td style="text-align: right;">77526</td>
<td style="text-align: right;">3875</td>
<td style="text-align: right;">45674</td>
</tr>
<tr class="even">
<td style="text-align: left;">Colusa</td>
<td style="text-align: right;">69619</td>
<td style="text-align: right;">5745</td>
<td style="text-align: right;">21811</td>
</tr>
</tbody>
</table>
</div>
</div>
</section>
<section id="data-quality-assessment" class="level2">
<h2 class="anchored" data-anchor-id="data-quality-assessment">2.2 Data Quality Assessment</h2>
<p><strong>Your Task:</strong> Calculate margin of error percentages and create reliability categories.</p>
<p><strong>Requirements:</strong> - Calculate MOE percentage: (margin of error / estimate) * 100 - Create reliability categories: - High Confidence: MOE &lt; 5% - Moderate Confidence: MOE 5-10%<br>
- Low Confidence: MOE &gt; 10% - Create a flag for unreliable estimates (MOE &gt; 10%)</p>
<p><strong>Hint:</strong> Use <code>mutate()</code> with <code>case_when()</code> for the categories.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb6"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Calculate MOE percentage and reliability categories using mutate()</span></span>
<span id="cb6-2"><a href="#cb6-2" aria-hidden="true" tabindex="-1"></a>ca_county_reliability <span class="ot">&lt;-</span> clean_data <span class="sc">%&gt;%</span></span>
<span id="cb6-3"><a href="#cb6-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(</span>
<span id="cb6-4"><a href="#cb6-4" aria-hidden="true" tabindex="-1"></a>    <span class="at">moe_pct =</span> (<span class="st">`</span><span class="at">Median HH Income Margin of Error</span><span class="st">`</span><span class="sc">/</span><span class="st">`</span><span class="at">Median Household Income</span><span class="st">`</span>)<span class="sc">*</span><span class="dv">100</span>,</span>
<span id="cb6-5"><a href="#cb6-5" aria-hidden="true" tabindex="-1"></a>    <span class="at">category =</span> <span class="fu">case_when</span>(</span>
<span id="cb6-6"><a href="#cb6-6" aria-hidden="true" tabindex="-1"></a>      moe_pct <span class="sc">&lt;</span> <span class="dv">5</span> <span class="sc">~</span> <span class="st">"High Confidence"</span>,</span>
<span id="cb6-7"><a href="#cb6-7" aria-hidden="true" tabindex="-1"></a>      moe_pct <span class="sc">&gt;=</span> <span class="dv">5</span> <span class="sc">&amp;</span> moe_pct <span class="sc">&lt;=</span> <span class="dv">10</span> <span class="sc">~</span> <span class="st">"Moderate Confidence"</span>,</span>
<span id="cb6-8"><a href="#cb6-8" aria-hidden="true" tabindex="-1"></a>      moe_pct <span class="sc">&gt;</span> <span class="dv">10</span> <span class="sc">~</span> <span class="st">"Low Confidence"</span></span>
<span id="cb6-9"><a href="#cb6-9" aria-hidden="true" tabindex="-1"></a>      ),</span>
<span id="cb6-10"><a href="#cb6-10" aria-hidden="true" tabindex="-1"></a>    <span class="at">flag =</span> <span class="fu">case_when</span>(category <span class="sc">==</span> <span class="st">"Low Confidence"</span> <span class="sc">~</span> <span class="st">"!!!"</span>,</span>
<span id="cb6-11"><a href="#cb6-11" aria-hidden="true" tabindex="-1"></a>                   <span class="cn">TRUE</span> <span class="sc">~</span> <span class="st">"    "</span>  )</span>
<span id="cb6-12"><a href="#cb6-12" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb6-13"><a href="#cb6-13" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb6-14"><a href="#cb6-14" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-15"><a href="#cb6-15" aria-hidden="true" tabindex="-1"></a><span class="fu">tibble</span>(ca_county_reliability)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 58 × 7
   County       Median Household Inc…¹ Median HH Income Mar…² `Total Population`
   &lt;chr&gt;                         &lt;dbl&gt;                  &lt;dbl&gt;              &lt;dbl&gt;
 1 Alameda                      122488                   1231            1663823
 2 Alpine                       101125                  17442               1515
 3 Amador                        74853                   6048              40577
 4 Butte                         66085                   2261             213605
 5 Calaveras                     77526                   3875              45674
 6 Colusa                        69619                   5745              21811
 7 Contra Costa                 120020                   1496            1162648
 8 Del Norte                     61149                   4376              27462
 9 El Dorado                     99246                   3330             191713
10 Fresno                        67756                    967            1008280
# ℹ 48 more rows
# ℹ abbreviated names: ¹​`Median Household Income`,
#   ²​`Median HH Income Margin of Error`
# ℹ 3 more variables: moe_pct &lt;dbl&gt;, category &lt;chr&gt;, flag &lt;chr&gt;</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb8"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Create a summary showing count of counties in each reliability category</span></span>
<span id="cb8-2"><a href="#cb8-2" aria-hidden="true" tabindex="-1"></a><span class="co"># Hint: use count() and mutate() to add percentages</span></span>
<span id="cb8-3"><a href="#cb8-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-4"><a href="#cb8-4" aria-hidden="true" tabindex="-1"></a>count_reliability <span class="ot">&lt;-</span> ca_county_reliability <span class="sc">%&gt;%</span></span>
<span id="cb8-5"><a href="#cb8-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">count</span>(category) <span class="sc">%&gt;%</span></span>
<span id="cb8-6"><a href="#cb8-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(</span>
<span id="cb8-7"><a href="#cb8-7" aria-hidden="true" tabindex="-1"></a>    <span class="at">percent =</span> n<span class="sc">/</span><span class="fu">sum</span>(n)<span class="sc">*</span><span class="dv">100</span></span>
<span id="cb8-8"><a href="#cb8-8" aria-hidden="true" tabindex="-1"></a>  )<span class="sc">%&gt;%</span></span>
<span id="cb8-9"><a href="#cb8-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(<span class="st">`</span><span class="at">Category of Reliability</span><span class="st">`</span> <span class="ot">=</span><span class="st">"category"</span>,</span>
<span id="cb8-10"><a href="#cb8-10" aria-hidden="true" tabindex="-1"></a>         <span class="st">`</span><span class="at">Count</span><span class="st">`</span><span class="ot">=</span> <span class="st">"n"</span>, </span>
<span id="cb8-11"><a href="#cb8-11" aria-hidden="true" tabindex="-1"></a>         <span class="st">`</span><span class="at">Percentage</span><span class="st">`</span><span class="ot">=</span> <span class="st">"percent"</span>)</span>
<span id="cb8-12"><a href="#cb8-12" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tibble</span>(count_reliability)<span class="sc">%&gt;%</span></span>
<span id="cb8-13"><a href="#cb8-13" aria-hidden="true" tabindex="-1"></a>    <span class="fu">kable</span>()</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<thead>
<tr class="header">
<th style="text-align: left;">Category of Reliability</th>
<th style="text-align: right;">Count</th>
<th style="text-align: right;">Percentage</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">High Confidence</td>
<td style="text-align: right;">42</td>
<td style="text-align: right;">72.41379</td>
</tr>
<tr class="even">
<td style="text-align: left;">Low Confidence</td>
<td style="text-align: right;">5</td>
<td style="text-align: right;">8.62069</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Moderate Confidence</td>
<td style="text-align: right;">11</td>
<td style="text-align: right;">18.96552</td>
</tr>
</tbody>
</table>
</div>
</div>
</section>
<section id="high-uncertainty-counties" class="level2">
<h2 class="anchored" data-anchor-id="high-uncertainty-counties">2.3 High Uncertainty Counties</h2>
<p><strong>Your Task:</strong> Identify the 5 counties with the highest MOE percentages.</p>
<p><strong>Requirements:</strong> - Sort by MOE percentage (highest first) - Select the top 5 counties - Display: county name, median income, margin of error, MOE percentage, reliability category - Format as a professional table using <code>kable()</code></p>
<p><strong>Hint:</strong> Use <code>arrange()</code>, <code>slice()</code>, and <code>select()</code> functions.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Create table of top 5 counties by MOE percentage</span></span>
<span id="cb9-2"><a href="#cb9-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-3"><a href="#cb9-3" aria-hidden="true" tabindex="-1"></a>top_variable <span class="ot">&lt;-</span> ca_county_reliability <span class="sc">%&gt;%</span></span>
<span id="cb9-4"><a href="#cb9-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">arrange</span>(<span class="fu">desc</span>(moe_pct))<span class="sc">%&gt;%</span></span>
<span id="cb9-5"><a href="#cb9-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">slice</span>(<span class="dv">1</span><span class="sc">:</span><span class="dv">5</span>) </span>
<span id="cb9-6"><a href="#cb9-6" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb9-7"><a href="#cb9-7" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(top_variable)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 5 × 7
  County  `Median Household Income` Median HH Income Margin…¹ `Total Population`
  &lt;chr&gt;                       &lt;dbl&gt;                     &lt;dbl&gt;              &lt;dbl&gt;
1 Mono                        82038                     15388              13219
2 Alpine                     101125                     17442               1515
3 Sierra                      61108                      9237               2916
4 Trinity                     47317                      5890              15889
5 Plumas                      67885                      7772              19650
# ℹ abbreviated name: ¹​`Median HH Income Margin of Error`
# ℹ 3 more variables: moe_pct &lt;dbl&gt;, category &lt;chr&gt;, flag &lt;chr&gt;</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb11"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Format as table with kable() - include appropriate column names and caption</span></span>
<span id="cb11-2"><a href="#cb11-2" aria-hidden="true" tabindex="-1"></a>top_variable <span class="ot">&lt;-</span> ca_county_reliability <span class="sc">%&gt;%</span></span>
<span id="cb11-3"><a href="#cb11-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">arrange</span>(<span class="fu">desc</span>(moe_pct)) <span class="sc">%&gt;%</span></span>
<span id="cb11-4"><a href="#cb11-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">slice</span>(<span class="dv">1</span><span class="sc">:</span><span class="dv">5</span>)</span>
<span id="cb11-5"><a href="#cb11-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-6"><a href="#cb11-6" aria-hidden="true" tabindex="-1"></a>top_variable <span class="sc">%&gt;%</span></span>
<span id="cb11-7"><a href="#cb11-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(</span>
<span id="cb11-8"><a href="#cb11-8" aria-hidden="true" tabindex="-1"></a>    County,</span>
<span id="cb11-9"><a href="#cb11-9" aria-hidden="true" tabindex="-1"></a>    <span class="st">`</span><span class="at">Median Household Income</span><span class="st">`</span>,</span>
<span id="cb11-10"><a href="#cb11-10" aria-hidden="true" tabindex="-1"></a>    <span class="st">`</span><span class="at">Median HH Income Margin of Error</span><span class="st">`</span>,</span>
<span id="cb11-11"><a href="#cb11-11" aria-hidden="true" tabindex="-1"></a>    <span class="st">`</span><span class="at">Total Population</span><span class="st">`</span>,</span>
<span id="cb11-12"><a href="#cb11-12" aria-hidden="true" tabindex="-1"></a>    <span class="st">`</span><span class="at">Margin of Error for HH Income (%)</span><span class="st">`</span> <span class="ot">=</span> moe_pct,</span>
<span id="cb11-13"><a href="#cb11-13" aria-hidden="true" tabindex="-1"></a>    <span class="st">`</span><span class="at">Reliability Category</span><span class="st">`</span> <span class="ot">=</span> category,</span>
<span id="cb11-14"><a href="#cb11-14" aria-hidden="true" tabindex="-1"></a>    <span class="at">DANGER =</span> flag</span>
<span id="cb11-15"><a href="#cb11-15" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">%&gt;%</span></span>
<span id="cb11-16"><a href="#cb11-16" aria-hidden="true" tabindex="-1"></a>  <span class="fu">kable</span>(<span class="at">caption =</span> <span class="st">"Top 5 counties in California by HH Income MOE"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<caption>Top 5 counties in California by HH Income MOE</caption>
<colgroup>
<col style="width: 5%">
<col style="width: 16%">
<col style="width: 22%">
<col style="width: 11%">
<col style="width: 23%">
<col style="width: 14%">
<col style="width: 4%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">County</th>
<th style="text-align: right;">Median Household Income</th>
<th style="text-align: right;">Median HH Income Margin of Error</th>
<th style="text-align: right;">Total Population</th>
<th style="text-align: right;">Margin of Error for HH Income (%)</th>
<th style="text-align: left;">Reliability Category</th>
<th style="text-align: left;">DANGER</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Mono</td>
<td style="text-align: right;">82038</td>
<td style="text-align: right;">15388</td>
<td style="text-align: right;">13219</td>
<td style="text-align: right;">18.75716</td>
<td style="text-align: left;">Low Confidence</td>
<td style="text-align: left;">!!!</td>
</tr>
<tr class="even">
<td style="text-align: left;">Alpine</td>
<td style="text-align: right;">101125</td>
<td style="text-align: right;">17442</td>
<td style="text-align: right;">1515</td>
<td style="text-align: right;">17.24796</td>
<td style="text-align: left;">Low Confidence</td>
<td style="text-align: left;">!!!</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Sierra</td>
<td style="text-align: right;">61108</td>
<td style="text-align: right;">9237</td>
<td style="text-align: right;">2916</td>
<td style="text-align: right;">15.11586</td>
<td style="text-align: left;">Low Confidence</td>
<td style="text-align: left;">!!!</td>
</tr>
<tr class="even">
<td style="text-align: left;">Trinity</td>
<td style="text-align: right;">47317</td>
<td style="text-align: right;">5890</td>
<td style="text-align: right;">15889</td>
<td style="text-align: right;">12.44796</td>
<td style="text-align: left;">Low Confidence</td>
<td style="text-align: left;">!!!</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Plumas</td>
<td style="text-align: right;">67885</td>
<td style="text-align: right;">7772</td>
<td style="text-align: right;">19650</td>
<td style="text-align: right;">11.44877</td>
<td style="text-align: left;">Low Confidence</td>
<td style="text-align: left;">!!!</td>
</tr>
</tbody>
</table>
</div>
</div>
<p><strong>Data Quality Commentary:</strong></p>
<p>[These results show that counties with the highest margins of error for median household income, such as Mono, Alpine, Sierra, Trinity, and Plumas, have less reliable income estimates. Algorithms that rely on this data may therefore poorly serve residents in these counties by producing unstable classifications or inaccurate eligibility decisions. This uncertainty may lead to their exclusion or misrepresentation in planning decisions and program targeting that depend on precise income thresholds.]</p>
</section>
</section>
<section id="part-3-neighborhood-level-analysis" class="level1">
<h1>Part 3: Neighborhood-Level Analysis</h1>
<section id="focus-area-selection" class="level2">
<h2 class="anchored" data-anchor-id="focus-area-selection">3.1 Focus Area Selection</h2>
<p><strong>Your Task:</strong> Select 2-3 counties from your reliability analysis for detailed tract-level study.</p>
<p><strong>Strategy:</strong> Choose counties that represent different reliability levels (e.g., 1 high confidence, 1 moderate, 1 low confidence) to compare how data quality varies.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb12"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Use filter() to select 2-3 counties from your county_reliability data</span></span>
<span id="cb12-2"><a href="#cb12-2" aria-hidden="true" tabindex="-1"></a><span class="co"># Store the selected counties in a variable called selected_counties</span></span>
<span id="cb12-3"><a href="#cb12-3" aria-hidden="true" tabindex="-1"></a><span class="co"># Display the selected counties with their key characteristics</span></span>
<span id="cb12-4"><a href="#cb12-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Show: county name, median income, MOE percentage, reliability category</span></span>
<span id="cb12-5"><a href="#cb12-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb12-6"><a href="#cb12-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb12-7"><a href="#cb12-7" aria-hidden="true" tabindex="-1"></a>selected_counties <span class="ot">&lt;-</span> ca_county_reliability <span class="sc">%&gt;%</span></span>
<span id="cb12-8"><a href="#cb12-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(category <span class="sc">%in%</span> <span class="fu">c</span>(<span class="st">"Low Confidence"</span>, <span class="st">"Moderate Confidence"</span>, <span class="st">"High Confidence"</span>)) <span class="sc">%&gt;%</span></span>
<span id="cb12-9"><a href="#cb12-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(category) <span class="sc">%&gt;%</span></span>
<span id="cb12-10"><a href="#cb12-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">slice</span>(<span class="dv">1</span>) <span class="sc">%&gt;%</span></span>
<span id="cb12-11"><a href="#cb12-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ungroup</span>() <span class="sc">%&gt;%</span></span>
<span id="cb12-12"><a href="#cb12-12" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(</span>
<span id="cb12-13"><a href="#cb12-13" aria-hidden="true" tabindex="-1"></a>    County,</span>
<span id="cb12-14"><a href="#cb12-14" aria-hidden="true" tabindex="-1"></a>    <span class="st">`</span><span class="at">Median Household Income</span><span class="st">`</span>,</span>
<span id="cb12-15"><a href="#cb12-15" aria-hidden="true" tabindex="-1"></a>    <span class="st">`</span><span class="at">Margin of Error for HH Income (%)</span><span class="st">`</span> <span class="ot">=</span> moe_pct,</span>
<span id="cb12-16"><a href="#cb12-16" aria-hidden="true" tabindex="-1"></a>    <span class="st">`</span><span class="at">Reliability Category</span><span class="st">`</span> <span class="ot">=</span> category,</span>
<span id="cb12-17"><a href="#cb12-17" aria-hidden="true" tabindex="-1"></a>  )</span>
<span id="cb12-18"><a href="#cb12-18" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb12-19"><a href="#cb12-19" aria-hidden="true" tabindex="-1"></a>selected_counties <span class="sc">%&gt;%</span> </span>
<span id="cb12-20"><a href="#cb12-20" aria-hidden="true" tabindex="-1"></a>  <span class="fu">kable</span>()</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<colgroup>
<col style="width: 9%">
<col style="width: 27%">
<col style="width: 39%">
<col style="width: 24%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">County</th>
<th style="text-align: right;">Median Household Income</th>
<th style="text-align: right;">Margin of Error for HH Income (%)</th>
<th style="text-align: left;">Reliability Category</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Alameda</td>
<td style="text-align: right;">122488</td>
<td style="text-align: right;">1.004996</td>
<td style="text-align: left;">High Confidence</td>
</tr>
<tr class="even">
<td style="text-align: left;">Alpine</td>
<td style="text-align: right;">101125</td>
<td style="text-align: right;">17.247960</td>
<td style="text-align: left;">Low Confidence</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Amador</td>
<td style="text-align: right;">74853</td>
<td style="text-align: right;">8.079837</td>
<td style="text-align: left;">Moderate Confidence</td>
</tr>
</tbody>
</table>
</div>
</div>
<p><strong>Comment on the output:</strong> The % cateogory of marginal error directly reflects the reliability of the data. Where, lower the % of marginal error, higher reliability of data.</p>
</section>
<section id="tract-level-demographics" class="level2">
<h2 class="anchored" data-anchor-id="tract-level-demographics">3.2 Tract-Level Demographics</h2>
<p><strong>Your Task:</strong> Get demographic data for census tracts in your selected counties.</p>
<p><strong>Requirements:</strong> - Geography: tract level - Variables: white alone (B03002_003), Black/African American (B03002_004), Hispanic/Latino (B03002_012), total population (B03002_001) - Use the same state and year as before - Output format: wide - <strong>Challenge:</strong> You’ll need county codes, not names. Look at the GEOID patterns in your county data for hints.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb13"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Define your race/ethnicity variables with descriptive names</span></span>
<span id="cb13-2"><a href="#cb13-2" aria-hidden="true" tabindex="-1"></a>race_variables <span class="ot">&lt;-</span> <span class="fu">c</span>(</span>
<span id="cb13-3"><a href="#cb13-3" aria-hidden="true" tabindex="-1"></a>  <span class="st">`</span><span class="at">White Alone</span><span class="st">`</span> <span class="ot">=</span> <span class="st">"B03002_003"</span>,</span>
<span id="cb13-4"><a href="#cb13-4" aria-hidden="true" tabindex="-1"></a>  <span class="st">`</span><span class="at">Black/African American</span><span class="st">`</span> <span class="ot">=</span> <span class="st">"B03002_004"</span>,</span>
<span id="cb13-5"><a href="#cb13-5" aria-hidden="true" tabindex="-1"></a>  <span class="st">`</span><span class="at">Hispanic/Latino</span><span class="st">`</span> <span class="ot">=</span> <span class="st">"B03002_012"</span>,</span>
<span id="cb13-6"><a href="#cb13-6" aria-hidden="true" tabindex="-1"></a>  <span class="st">`</span><span class="at">Total Population</span><span class="st">`</span> <span class="ot">=</span> <span class="st">"B03002_001"</span></span>
<span id="cb13-7"><a href="#cb13-7" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb13-8"><a href="#cb13-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-9"><a href="#cb13-9" aria-hidden="true" tabindex="-1"></a><span class="co"># Use get_acs() to retrieve tract-level data</span></span>
<span id="cb13-10"><a href="#cb13-10" aria-hidden="true" tabindex="-1"></a><span class="co"># Hint: You may need to specify county codes in the county parameter</span></span>
<span id="cb13-11"><a href="#cb13-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-12"><a href="#cb13-12" aria-hidden="true" tabindex="-1"></a>county_levelcode <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">"001"</span>,<span class="st">"003"</span>,<span class="st">"005"</span>)</span>
<span id="cb13-13"><a href="#cb13-13" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb13-14"><a href="#cb13-14" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-15"><a href="#cb13-15" aria-hidden="true" tabindex="-1"></a>selected_counties_data <span class="ot">&lt;-</span> <span class="fu">get_acs</span>(</span>
<span id="cb13-16"><a href="#cb13-16" aria-hidden="true" tabindex="-1"></a>  <span class="at">geography =</span> <span class="st">"tract"</span>,</span>
<span id="cb13-17"><a href="#cb13-17" aria-hidden="true" tabindex="-1"></a>  <span class="at">variables =</span> race_variables,</span>
<span id="cb13-18"><a href="#cb13-18" aria-hidden="true" tabindex="-1"></a>  <span class="at">county =</span> county_levelcode,</span>
<span id="cb13-19"><a href="#cb13-19" aria-hidden="true" tabindex="-1"></a>  <span class="at">state =</span> my_state,</span>
<span id="cb13-20"><a href="#cb13-20" aria-hidden="true" tabindex="-1"></a>  <span class="at">year =</span> <span class="dv">2022</span>,</span>
<span id="cb13-21"><a href="#cb13-21" aria-hidden="true" tabindex="-1"></a>  <span class="at">survey =</span> <span class="st">"acs5"</span>,</span>
<span id="cb13-22"><a href="#cb13-22" aria-hidden="true" tabindex="-1"></a>  <span class="at">output =</span> <span class="st">"wide"</span></span>
<span id="cb13-23"><a href="#cb13-23" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb13-24"><a href="#cb13-24" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-25"><a href="#cb13-25" aria-hidden="true" tabindex="-1"></a><span class="fu">tibble</span>(selected_counties_data)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 390 × 10
   GEOID       NAME         `White AloneE` `White AloneM` Black/African Americ…¹
   &lt;chr&gt;       &lt;chr&gt;                 &lt;dbl&gt;          &lt;dbl&gt;                  &lt;dbl&gt;
 1 06001400100 Census Trac…           2255            444                    171
 2 06001400200 Census Trac…           1500            219                     38
 3 06001400300 Census Trac…           3290            378                    529
 4 06001400400 Census Trac…           2740            606                    499
 5 06001400500 Census Trac…           1638            262                    993
 6 06001400600 Census Trac…            905            183                    539
 7 06001400700 Census Trac…           2293            422                   1101
 8 06001400800 Census Trac…           2228            462                    643
 9 06001400900 Census Trac…           1052            266                    692
10 06001401000 Census Trac…           2095            531                   1478
# ℹ 380 more rows
# ℹ abbreviated name: ¹​`Black/African AmericanE`
# ℹ 5 more variables: `Black/African AmericanM` &lt;dbl&gt;,
#   `Hispanic/LatinoE` &lt;dbl&gt;, `Hispanic/LatinoM` &lt;dbl&gt;,
#   `Total PopulationE` &lt;dbl&gt;, `Total PopulationM` &lt;dbl&gt;</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb15"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Calculate percentage of each group using mutate()</span></span>
<span id="cb15-2"><a href="#cb15-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-3"><a href="#cb15-3" aria-hidden="true" tabindex="-1"></a>percentage_eachgroup <span class="ot">&lt;-</span> selected_counties_data <span class="sc">%&gt;%</span></span>
<span id="cb15-4"><a href="#cb15-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(</span>
<span id="cb15-5"><a href="#cb15-5" aria-hidden="true" tabindex="-1"></a>    <span class="at">pct_white =</span> (<span class="st">`</span><span class="at">White AloneE</span><span class="st">`</span><span class="sc">/</span><span class="st">`</span><span class="at">Total PopulationE</span><span class="st">`</span>)<span class="sc">*</span><span class="dv">100</span>,</span>
<span id="cb15-6"><a href="#cb15-6" aria-hidden="true" tabindex="-1"></a>    <span class="at">pct_Black =</span> (<span class="st">`</span><span class="at">Black/African AmericanE</span><span class="st">`</span><span class="sc">/</span><span class="st">`</span><span class="at">Total PopulationE</span><span class="st">`</span>)<span class="sc">*</span><span class="dv">100</span>,</span>
<span id="cb15-7"><a href="#cb15-7" aria-hidden="true" tabindex="-1"></a>    <span class="at">pct_Hisp =</span> (<span class="st">`</span><span class="at">Hispanic/LatinoE</span><span class="st">`</span><span class="sc">/</span><span class="st">`</span><span class="at">Total PopulationE</span><span class="st">`</span>)<span class="sc">*</span><span class="dv">100</span></span>
<span id="cb15-8"><a href="#cb15-8" aria-hidden="true" tabindex="-1"></a>    ) <span class="sc">%&gt;%</span></span>
<span id="cb15-9"><a href="#cb15-9" aria-hidden="true" tabindex="-1"></a>  <span class="co"># Create percentages for white, Black, and Hispanic populations</span></span>
<span id="cb15-10"><a href="#cb15-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="st">`</span><span class="at">Percentage of White, Black and Hispanic Populations</span><span class="st">`</span><span class="ot">=</span> pct_white <span class="sc">+</span> pct_Black <span class="sc">+</span> pct_Hisp, </span>
<span id="cb15-11"><a href="#cb15-11" aria-hidden="true" tabindex="-1"></a> <span class="co"># Add readable tract and county name columns using str_extract() or similar</span></span>
<span id="cb15-12"><a href="#cb15-12" aria-hidden="true" tabindex="-1"></a>         <span class="at">Tract =</span>  <span class="fu">str_extract</span>(NAME, <span class="st">"[0-9.]+"</span>),</span>
<span id="cb15-13"><a href="#cb15-13" aria-hidden="true" tabindex="-1"></a>         <span class="at">County =</span> <span class="fu">str_extract</span>(NAME, <span class="st">"[A-Za-z ]+ County"</span>))<span class="sc">%&gt;%</span> </span>
<span id="cb15-14"><a href="#cb15-14" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(County, Tract,</span>
<span id="cb15-15"><a href="#cb15-15" aria-hidden="true" tabindex="-1"></a>         <span class="st">`</span><span class="at">White %</span><span class="st">`</span> <span class="ot">=</span> <span class="st">"pct_white"</span>,</span>
<span id="cb15-16"><a href="#cb15-16" aria-hidden="true" tabindex="-1"></a>         <span class="st">`</span><span class="at">Black %</span><span class="st">`</span><span class="ot">=</span> <span class="st">"pct_Black"</span>,</span>
<span id="cb15-17"><a href="#cb15-17" aria-hidden="true" tabindex="-1"></a>         <span class="st">`</span><span class="at">Hispanic or Latino %</span><span class="st">`</span><span class="ot">=</span><span class="st">"pct_Hisp"</span>, </span>
<span id="cb15-18"><a href="#cb15-18" aria-hidden="true" tabindex="-1"></a>         <span class="st">`</span><span class="at">Percentage of White, Black and Hispanic Populations</span><span class="st">`</span>,</span>
<span id="cb15-19"><a href="#cb15-19" aria-hidden="true" tabindex="-1"></a>        )</span>
<span id="cb15-20"><a href="#cb15-20" aria-hidden="true" tabindex="-1"></a><span class="fu">tibble</span>(percentage_eachgroup)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 390 × 6
   County            Tract `White %` `Black %` `Hispanic or Latino %`
   &lt;chr&gt;             &lt;chr&gt;     &lt;dbl&gt;     &lt;dbl&gt;                  &lt;dbl&gt;
 1 " Alameda County" 4001       69.0      5.23                   5.11
 2 " Alameda County" 4002       69.9      1.77                   7.41
 3 " Alameda County" 4003       58.6      9.41                  10.1 
 4 " Alameda County" 4004       64.0     11.7                    7.15
 5 " Alameda County" 4005       41.5     25.1                   15.5 
 6 " Alameda County" 4006       44.0     26.2                    6.51
 7 " Alameda County" 4007       48.2     23.1                    9.88
 8 " Alameda County" 4008       51.4     14.8                    8.93
 9 " Alameda County" 4009       37.0     24.3                   18.7 
10 " Alameda County" 4010       33.4     23.5                   22.1 
# ℹ 380 more rows
# ℹ 1 more variable:
#   `Percentage of White, Black and Hispanic Populations` &lt;dbl&gt;</code></pre>
</div>
</div>
</section>
<section id="demographic-analysis" class="level2">
<h2 class="anchored" data-anchor-id="demographic-analysis">3.3 Demographic Analysis</h2>
<p><strong>Your Task:</strong> Analyze the demographic patterns in your selected areas.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb17"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Find the tract with the highest percentage of Hispanic/Latino residents</span></span>
<span id="cb17-2"><a href="#cb17-2" aria-hidden="true" tabindex="-1"></a><span class="co"># Hint: use arrange() and slice() to get the top tract</span></span>
<span id="cb17-3"><a href="#cb17-3" aria-hidden="true" tabindex="-1"></a>hisp_high <span class="ot">&lt;-</span> percentage_eachgroup <span class="sc">%&gt;%</span></span>
<span id="cb17-4"><a href="#cb17-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">arrange</span>(<span class="fu">desc</span>(<span class="st">`</span><span class="at">Hispanic or Latino %</span><span class="st">`</span>))<span class="sc">%&gt;%</span></span>
<span id="cb17-5"><a href="#cb17-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">slice_head</span>(<span class="at">n=</span><span class="dv">1</span>)<span class="sc">%&gt;%</span></span>
<span id="cb17-6"><a href="#cb17-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(County,<span class="st">`</span><span class="at">Hispanic or Latino %</span><span class="st">`</span>)</span>
<span id="cb17-7"><a href="#cb17-7" aria-hidden="true" tabindex="-1"></a><span class="fu">tibble</span>(hisp_high)<span class="sc">%&gt;%</span></span>
<span id="cb17-8"><a href="#cb17-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">kable</span>()</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<thead>
<tr class="header">
<th style="text-align: left;">County</th>
<th style="text-align: right;">Hispanic or Latino %</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Alameda County</td>
<td style="text-align: right;">85</td>
</tr>
</tbody>
</table>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb18"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Calculate average demographics by county using group_by() and summarize()</span></span>
<span id="cb18-2"><a href="#cb18-2" aria-hidden="true" tabindex="-1"></a><span class="co"># Show: number of tracts, average percentage for each racial/ethnic group</span></span>
<span id="cb18-3"><a href="#cb18-3" aria-hidden="true" tabindex="-1"></a>county_summary <span class="ot">&lt;-</span> percentage_eachgroup <span class="sc">%&gt;%</span></span>
<span id="cb18-4"><a href="#cb18-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(County)<span class="sc">%&gt;%</span></span>
<span id="cb18-5"><a href="#cb18-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(<span class="st">`</span><span class="at">Number of Tracts</span><span class="st">`</span><span class="ot">=</span><span class="fu">n</span>(),</span>
<span id="cb18-6"><a href="#cb18-6" aria-hidden="true" tabindex="-1"></a>            <span class="st">`</span><span class="at">Average White Percentage</span><span class="st">`</span> <span class="ot">=</span> <span class="fu">mean</span>(<span class="st">`</span><span class="at">White %</span><span class="st">`</span>, <span class="at">na.rm =</span> <span class="cn">TRUE</span>),</span>
<span id="cb18-7"><a href="#cb18-7" aria-hidden="true" tabindex="-1"></a>            <span class="st">`</span><span class="at">Average Black Percentage</span><span class="st">`</span> <span class="ot">=</span> <span class="fu">mean</span>(<span class="st">`</span><span class="at">Black %</span><span class="st">`</span>, <span class="at">na.rm =</span> <span class="cn">TRUE</span>),</span>
<span id="cb18-8"><a href="#cb18-8" aria-hidden="true" tabindex="-1"></a>            <span class="st">`</span><span class="at">Average Hispanic Percentage</span><span class="st">`</span> <span class="ot">=</span> <span class="fu">mean</span>(<span class="st">`</span><span class="at">Hispanic or Latino %</span><span class="st">`</span>, <span class="at">na.rm =</span> <span class="cn">TRUE</span>)</span>
<span id="cb18-9"><a href="#cb18-9" aria-hidden="true" tabindex="-1"></a>    </span>
<span id="cb18-10"><a href="#cb18-10" aria-hidden="true" tabindex="-1"></a>  )<span class="sc">%&gt;%</span></span>
<span id="cb18-11"><a href="#cb18-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(</span>
<span id="cb18-12"><a href="#cb18-12" aria-hidden="true" tabindex="-1"></a>    County,</span>
<span id="cb18-13"><a href="#cb18-13" aria-hidden="true" tabindex="-1"></a>    <span class="st">`</span><span class="at">Number of Tracts</span><span class="st">`</span>,</span>
<span id="cb18-14"><a href="#cb18-14" aria-hidden="true" tabindex="-1"></a>    <span class="st">`</span><span class="at">Average White Percentage</span><span class="st">`</span>,</span>
<span id="cb18-15"><a href="#cb18-15" aria-hidden="true" tabindex="-1"></a>    <span class="st">`</span><span class="at">Average Black Percentage</span><span class="st">`</span>,</span>
<span id="cb18-16"><a href="#cb18-16" aria-hidden="true" tabindex="-1"></a>    <span class="st">`</span><span class="at">Average Hispanic Percentage</span><span class="st">`</span></span>
<span id="cb18-17"><a href="#cb18-17" aria-hidden="true" tabindex="-1"></a>    )</span>
<span id="cb18-18"><a href="#cb18-18" aria-hidden="true" tabindex="-1"></a><span class="fu">tibble</span>(county_summary)<span class="sc">%&gt;%</span> </span>
<span id="cb18-19"><a href="#cb18-19" aria-hidden="true" tabindex="-1"></a>  <span class="fu">kable</span>()</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<colgroup>
<col style="width: 13%">
<col style="width: 15%">
<col style="width: 22%">
<col style="width: 22%">
<col style="width: 25%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">County</th>
<th style="text-align: right;">Number of Tracts</th>
<th style="text-align: right;">Average White Percentage</th>
<th style="text-align: right;">Average Black Percentage</th>
<th style="text-align: right;">Average Hispanic Percentage</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Alameda County</td>
<td style="text-align: right;">379</td>
<td style="text-align: right;">31.03341</td>
<td style="text-align: right;">10.70641</td>
<td style="text-align: right;">21.38505</td>
</tr>
<tr class="even">
<td style="text-align: left;">Alpine County</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">58.08581</td>
<td style="text-align: right;">0.00000</td>
<td style="text-align: right;">14.05941</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Amador County</td>
<td style="text-align: right;">10</td>
<td style="text-align: right;">75.66480</td>
<td style="text-align: right;">1.55211</td>
<td style="text-align: right;">14.87333</td>
</tr>
</tbody>
</table>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb19"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Create a nicely formatted table of your results using kable()</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
</section>
</section>
<section id="part-4-comprehensive-data-quality-evaluation" class="level1">
<h1>Part 4: Comprehensive Data Quality Evaluation</h1>
<section id="moe-analysis-for-demographic-variables" class="level2">
<h2 class="anchored" data-anchor-id="moe-analysis-for-demographic-variables">4.1 MOE Analysis for Demographic Variables</h2>
<p><strong>Your Task:</strong> Examine margins of error for demographic variables to see if some communities have less reliable data.</p>
<p><strong>Requirements:</strong> - Calculate MOE percentages for each demographic variable - Flag tracts where any demographic variable has MOE &gt; 15% - Create summary statistics</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb20"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Calculate MOE percentages for white, Black, and Hispanic variables</span></span>
<span id="cb20-2"><a href="#cb20-2" aria-hidden="true" tabindex="-1"></a><span class="co"># Hint: use the same formula as before (margin/estimate * 100)</span></span>
<span id="cb20-3"><a href="#cb20-3" aria-hidden="true" tabindex="-1"></a><span class="fu">tibble</span>(selected_counties_data)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 390 × 10
   GEOID       NAME         `White AloneE` `White AloneM` Black/African Americ…¹
   &lt;chr&gt;       &lt;chr&gt;                 &lt;dbl&gt;          &lt;dbl&gt;                  &lt;dbl&gt;
 1 06001400100 Census Trac…           2255            444                    171
 2 06001400200 Census Trac…           1500            219                     38
 3 06001400300 Census Trac…           3290            378                    529
 4 06001400400 Census Trac…           2740            606                    499
 5 06001400500 Census Trac…           1638            262                    993
 6 06001400600 Census Trac…            905            183                    539
 7 06001400700 Census Trac…           2293            422                   1101
 8 06001400800 Census Trac…           2228            462                    643
 9 06001400900 Census Trac…           1052            266                    692
10 06001401000 Census Trac…           2095            531                   1478
# ℹ 380 more rows
# ℹ abbreviated name: ¹​`Black/African AmericanE`
# ℹ 5 more variables: `Black/African AmericanM` &lt;dbl&gt;,
#   `Hispanic/LatinoE` &lt;dbl&gt;, `Hispanic/LatinoM` &lt;dbl&gt;,
#   `Total PopulationE` &lt;dbl&gt;, `Total PopulationM` &lt;dbl&gt;</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb22"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a>moe_race <span class="ot">&lt;-</span> selected_counties_data <span class="sc">%&gt;%</span></span>
<span id="cb22-2"><a href="#cb22-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(</span>
<span id="cb22-3"><a href="#cb22-3" aria-hidden="true" tabindex="-1"></a>    <span class="st">`</span><span class="at">MOE % White</span><span class="st">`</span> <span class="ot">=</span> (<span class="st">`</span><span class="at">White AloneM</span><span class="st">`</span> <span class="sc">/</span> <span class="st">`</span><span class="at">White AloneE</span><span class="st">`</span>)<span class="sc">*</span><span class="dv">100</span>,</span>
<span id="cb22-4"><a href="#cb22-4" aria-hidden="true" tabindex="-1"></a>    <span class="st">`</span><span class="at">MOE % Black</span><span class="st">`</span> <span class="ot">=</span> (<span class="st">`</span><span class="at">Black/African AmericanM</span><span class="st">`</span> <span class="sc">/</span> <span class="st">`</span><span class="at">Black/African AmericanE</span><span class="st">`</span>)<span class="sc">*</span><span class="dv">100</span>,</span>
<span id="cb22-5"><a href="#cb22-5" aria-hidden="true" tabindex="-1"></a>    <span class="st">`</span><span class="at">MOE % Hispanic</span><span class="st">`</span> <span class="ot">=</span> (<span class="st">`</span><span class="at">Hispanic/LatinoM</span><span class="st">`</span> <span class="sc">/</span> <span class="st">`</span><span class="at">Hispanic/LatinoE</span><span class="st">`</span>)<span class="sc">*</span><span class="dv">100</span>,</span>
<span id="cb22-6"><a href="#cb22-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb22-7"><a href="#cb22-7" aria-hidden="true" tabindex="-1"></a><span class="co"># Create a flag for tracts with high MOE on any demographic variable</span></span>
<span id="cb22-8"><a href="#cb22-8" aria-hidden="true" tabindex="-1"></a><span class="co"># Use logical operators (| for OR) in an ifelse() statement</span></span>
<span id="cb22-9"><a href="#cb22-9" aria-hidden="true" tabindex="-1"></a><span class="at">Flag =</span> <span class="fu">ifelse</span>(</span>
<span id="cb22-10"><a href="#cb22-10" aria-hidden="true" tabindex="-1"></a>     <span class="st">`</span><span class="at">MOE % White</span><span class="st">`</span> <span class="sc">&gt;</span> <span class="dv">15</span> <span class="sc">|</span> <span class="st">`</span><span class="at">MOE % Black</span><span class="st">`</span> <span class="sc">&gt;</span> <span class="dv">15</span> <span class="sc">|</span> <span class="st">`</span><span class="at">MOE % Hispanic</span><span class="st">`</span> <span class="sc">&gt;</span> <span class="dv">15</span>, <span class="st">"UNRELIABLE"</span>, <span class="st">"  "</span>)</span>
<span id="cb22-11"><a href="#cb22-11" aria-hidden="true" tabindex="-1"></a>    )</span>
<span id="cb22-12"><a href="#cb22-12" aria-hidden="true" tabindex="-1"></a><span class="fu">tibble</span>(moe_race)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 390 × 14
   GEOID       NAME         `White AloneE` `White AloneM` Black/African Americ…¹
   &lt;chr&gt;       &lt;chr&gt;                 &lt;dbl&gt;          &lt;dbl&gt;                  &lt;dbl&gt;
 1 06001400100 Census Trac…           2255            444                    171
 2 06001400200 Census Trac…           1500            219                     38
 3 06001400300 Census Trac…           3290            378                    529
 4 06001400400 Census Trac…           2740            606                    499
 5 06001400500 Census Trac…           1638            262                    993
 6 06001400600 Census Trac…            905            183                    539
 7 06001400700 Census Trac…           2293            422                   1101
 8 06001400800 Census Trac…           2228            462                    643
 9 06001400900 Census Trac…           1052            266                    692
10 06001401000 Census Trac…           2095            531                   1478
# ℹ 380 more rows
# ℹ abbreviated name: ¹​`Black/African AmericanE`
# ℹ 9 more variables: `Black/African AmericanM` &lt;dbl&gt;,
#   `Hispanic/LatinoE` &lt;dbl&gt;, `Hispanic/LatinoM` &lt;dbl&gt;,
#   `Total PopulationE` &lt;dbl&gt;, `Total PopulationM` &lt;dbl&gt;, `MOE % White` &lt;dbl&gt;,
#   `MOE % Black` &lt;dbl&gt;, `MOE % Hispanic` &lt;dbl&gt;, Flag &lt;chr&gt;</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb24"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb24-1"><a href="#cb24-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Create summary statistics showing how many tracts have data quality issues</span></span>
<span id="cb24-2"><a href="#cb24-2" aria-hidden="true" tabindex="-1"></a>summary <span class="ot">&lt;-</span> moe_race <span class="sc">%&gt;%</span> </span>
<span id="cb24-3"><a href="#cb24-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(</span>
<span id="cb24-4"><a href="#cb24-4" aria-hidden="true" tabindex="-1"></a>  <span class="at">tracts =</span> <span class="fu">n</span>(),</span>
<span id="cb24-5"><a href="#cb24-5" aria-hidden="true" tabindex="-1"></a>  <span class="st">`</span><span class="at">tracts with issues</span><span class="st">`</span> <span class="ot">=</span> <span class="fu">sum</span>(Flag <span class="sc">==</span> <span class="st">"UNRELIABLE"</span>)</span>
<span id="cb24-6"><a href="#cb24-6" aria-hidden="true" tabindex="-1"></a>) </span>
<span id="cb24-7"><a href="#cb24-7" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(summary)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 1 × 2
  tracts `tracts with issues`
   &lt;int&gt;                &lt;int&gt;
1    390                  390</code></pre>
</div>
</div>
</section>
<section id="pattern-analysis" class="level2">
<h2 class="anchored" data-anchor-id="pattern-analysis">4.2 Pattern Analysis</h2>
<p><strong>Your Task:</strong> Investigate whether data quality problems are randomly distributed or concentrated in certain types of communities.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb26"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb26-1"><a href="#cb26-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Group tracts by whether they have high MOE issues</span></span>
<span id="cb26-2"><a href="#cb26-2" aria-hidden="true" tabindex="-1"></a><span class="co"># Calculate average characteristics for each group:</span></span>
<span id="cb26-3"><a href="#cb26-3" aria-hidden="true" tabindex="-1"></a><span class="co"># - population size, demographic percentages</span></span>
<span id="cb26-4"><a href="#cb26-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Use group_by() and summarize() to create this comparison</span></span>
<span id="cb26-5"><a href="#cb26-5" aria-hidden="true" tabindex="-1"></a><span class="co"># Create a professional table showing the patterns</span></span>
<span id="cb26-6"><a href="#cb26-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb26-7"><a href="#cb26-7" aria-hidden="true" tabindex="-1"></a>moe_issuesummary <span class="ot">&lt;-</span> moe_race <span class="sc">%&gt;%</span></span>
<span id="cb26-8"><a href="#cb26-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(Flag) <span class="sc">%&gt;%</span></span>
<span id="cb26-9"><a href="#cb26-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(</span>
<span id="cb26-10"><a href="#cb26-10" aria-hidden="true" tabindex="-1"></a>    <span class="at">tracts =</span> <span class="fu">n</span>(),</span>
<span id="cb26-11"><a href="#cb26-11" aria-hidden="true" tabindex="-1"></a>    <span class="st">`</span><span class="at">Average Population</span><span class="st">`</span> <span class="ot">=</span> <span class="fu">mean</span>(<span class="st">`</span><span class="at">Total PopulationE</span><span class="st">`</span>, <span class="at">na.rm =</span> <span class="cn">TRUE</span>),</span>
<span id="cb26-12"><a href="#cb26-12" aria-hidden="true" tabindex="-1"></a>    <span class="st">`</span><span class="at">Average White Population %</span><span class="st">`</span> <span class="ot">=</span> <span class="fu">mean</span>((<span class="st">`</span><span class="at">White AloneE</span><span class="st">`</span> <span class="sc">/</span> <span class="st">`</span><span class="at">Total PopulationE</span><span class="st">`</span>) <span class="sc">*</span> <span class="dv">100</span>, <span class="at">na.rm =</span> <span class="cn">TRUE</span>),</span>
<span id="cb26-13"><a href="#cb26-13" aria-hidden="true" tabindex="-1"></a>    <span class="st">`</span><span class="at">Average Black Population %</span><span class="st">`</span> <span class="ot">=</span> <span class="fu">mean</span>((<span class="st">`</span><span class="at">Black/African AmericanE</span><span class="st">`</span> <span class="sc">/</span> <span class="st">`</span><span class="at">Total PopulationE</span><span class="st">`</span>) <span class="sc">*</span> <span class="dv">100</span>, <span class="at">na.rm =</span> <span class="cn">TRUE</span>),</span>
<span id="cb26-14"><a href="#cb26-14" aria-hidden="true" tabindex="-1"></a>    <span class="st">`</span><span class="at">Average Hispanic Population %</span><span class="st">`</span> <span class="ot">=</span> <span class="fu">mean</span>((<span class="st">`</span><span class="at">Hispanic/LatinoE</span><span class="st">`</span> <span class="sc">/</span> <span class="st">`</span><span class="at">Total PopulationE</span><span class="st">`</span>) <span class="sc">*</span> <span class="dv">100</span>, <span class="at">na.rm =</span> <span class="cn">TRUE</span>)</span>
<span id="cb26-15"><a href="#cb26-15" aria-hidden="true" tabindex="-1"></a>  )</span>
<span id="cb26-16"><a href="#cb26-16" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb26-17"><a href="#cb26-17" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tibble</span>(moe_issuesummary) <span class="sc">%&gt;%</span></span>
<span id="cb26-18"><a href="#cb26-18" aria-hidden="true" tabindex="-1"></a>  <span class="fu">kable</span>(</span>
<span id="cb26-19"><a href="#cb26-19" aria-hidden="true" tabindex="-1"></a>    <span class="at">caption =</span> <span class="st">"Average Tract Characteristics by Data Quality Status"</span></span>
<span id="cb26-20"><a href="#cb26-20" aria-hidden="true" tabindex="-1"></a>  )</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<caption>Average Tract Characteristics by Data Quality Status</caption>
<colgroup>
<col style="width: 9%">
<col style="width: 5%">
<col style="width: 15%">
<col style="width: 22%">
<col style="width: 22%">
<col style="width: 24%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">Flag</th>
<th style="text-align: right;">tracts</th>
<th style="text-align: right;">Average Population</th>
<th style="text-align: right;">Average White Population %</th>
<th style="text-align: right;">Average Black Population %</th>
<th style="text-align: right;">Average Hispanic Population %</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">UNRELIABLE</td>
<td style="text-align: right;">390</td>
<td style="text-align: right;">4374.141</td>
<td style="text-align: right;">32.25342</td>
<td style="text-align: right;">10.44288</td>
<td style="text-align: right;">21.19834</td>
</tr>
</tbody>
</table>
</div>
</div>
<p><strong>Pattern Analysis:</strong> In my selected counties, all 390 census tracts are flagged as unreliable, meaning there is no meaningful contrast between reliable and unreliable areas. These tracts are relatively small, with an average population of about 4,374 residents, which helps explain the uniformly high margins of error. While White, Black, and Hispanic populations are present at non-negligible levels across tracts, the high uncertainty affects all groups similarly, indicating that unreliability is driven primarily by small population sizes and ACS sampling limitations rather than demographic composition. As a result, tract-level estimates in these counties are particularly vulnerable to error, making them risky inputs for algorithmic decision-making that depends on precise demographic thresholds.</p>
</section>
</section>
<section id="part-5-policy-recommendations" class="level1">
<h1>Part 5: Policy Recommendations</h1>
<section id="analysis-integration-and-professional-summary" class="level2">
<h2 class="anchored" data-anchor-id="analysis-integration-and-professional-summary">5.1 Analysis Integration and Professional Summary</h2>
<p><strong>Your Task:</strong> Write an executive summary that integrates findings from all four analyses.</p>
<p><strong>Executive Summary Requirements:</strong> 1. <strong>Overall Pattern Identification</strong>: What are the systematic patterns across all your analyses? 2. <strong>Equity Assessment</strong>: Which communities face the greatest risk of algorithmic bias based on your findings? 3. <strong>Root Cause Analysis</strong>: What underlying factors drive both data quality issues and bias risk? 4. <strong>Strategic Recommendations</strong>: What should the Department implement to address these systematic issues?</p>
<p><strong>Executive Summary:</strong></p>
<p>The overall analysis focused on the reliability of ACS data for median household income at the county level and racial and ethnic composition at the census-tract level shows a clear understanding of how data reliability varies across measures. Data reliability differs by both variable and geographic or political division. County-level income estimates are mostly reliable, with almost 70 percent of counties providing data where the margin of error falls below 5 percent. In contrast, census-tract-level racial composition data are largely unreliable. For the randomly selected counties, regardless of income data reliability, racial data reliability remained consistently low. Out of 390 census tracts analyzed, all exhibited unreliable racial or ethnic estimates failing the 15% threshold.</p>
<p>Data reliability is especially weak for race and ethnicity variables, primarily because margins of error are high across tracts. This suggests a need to reconsider current data collection approaches. Census tracts in the analysis have relatively small populations, averaging around 4,000 residents. A general inference from the results is that smaller population sizes are associated with higher margins of error. As a result, existing ACS sampling and data collection methods may require revision to produce more reliable tract-level estimates.</p>
<p>The root cause of these issues appears to lie in the sampling design and overall data collection methodology. Capturing a larger effective sample would be necessary to improve reliability. In the long term, reconsidering census tract sizing or adopting alternative aggregation strategies may be necessary to support more stable and reliable data collection in the future.</p>
<p>The Department of Human Services should adopt an uncertainty-aware approach to decision-making by incorporating margins of error directly into analytical and algorithmic processes rather than relying on point estimates alone. Census tract level racial and ethnic composition data should not be used in isolation under current reliability conditions and should instead be aggregated to higher geographies or supplemented with additional data. A tiered framework based on data reliability should guide when automated decisions are appropriate versus when further review is required. Finally, reliability flags and margin of error measures should be clearly documented and carried through all outputs so uncertainty is visible at the point of decision</p>
</section>
<section id="specific-recommendations" class="level2">
<h2 class="anchored" data-anchor-id="specific-recommendations">6.3 Specific Recommendations</h2>
<p><strong>Your Task:</strong> Create a decision framework for algorithm implementation.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb27"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb27-1"><a href="#cb27-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Create a summary table using your county reliability data</span></span>
<span id="cb27-2"><a href="#cb27-2" aria-hidden="true" tabindex="-1"></a><span class="co"># Include: county name, median income, MOE percentage, reliability category</span></span>
<span id="cb27-3"><a href="#cb27-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb27-4"><a href="#cb27-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Add a new column with algorithm recommendations using case_when():</span></span>
<span id="cb27-5"><a href="#cb27-5" aria-hidden="true" tabindex="-1"></a><span class="co"># - High Confidence: "Safe for algorithmic decisions"</span></span>
<span id="cb27-6"><a href="#cb27-6" aria-hidden="true" tabindex="-1"></a><span class="co"># - Moderate Confidence: "Use with caution - monitor outcomes"  </span></span>
<span id="cb27-7"><a href="#cb27-7" aria-hidden="true" tabindex="-1"></a><span class="co"># - Low Confidence: "Requires manual review or additional data"</span></span>
<span id="cb27-8"><a href="#cb27-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb27-9"><a href="#cb27-9" aria-hidden="true" tabindex="-1"></a><span class="co"># Format as a professional table with kable()</span></span>
<span id="cb27-10"><a href="#cb27-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb27-11"><a href="#cb27-11" aria-hidden="true" tabindex="-1"></a>summary_overall <span class="ot">&lt;-</span> ca_county_reliability <span class="sc">%&gt;%</span></span>
<span id="cb27-12"><a href="#cb27-12" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(</span>
<span id="cb27-13"><a href="#cb27-13" aria-hidden="true" tabindex="-1"></a>    County,</span>
<span id="cb27-14"><a href="#cb27-14" aria-hidden="true" tabindex="-1"></a>    <span class="st">`</span><span class="at">Median Household Income</span><span class="st">`</span>,</span>
<span id="cb27-15"><a href="#cb27-15" aria-hidden="true" tabindex="-1"></a>    <span class="st">`</span><span class="at">Margin of Error for HH Income (%)</span><span class="st">`</span> <span class="ot">=</span> moe_pct, </span>
<span id="cb27-16"><a href="#cb27-16" aria-hidden="true" tabindex="-1"></a>    <span class="st">`</span><span class="at">Reliability Category</span><span class="st">`</span> <span class="ot">=</span> category</span>
<span id="cb27-17"><a href="#cb27-17" aria-hidden="true" tabindex="-1"></a>  )<span class="sc">%&gt;%</span></span>
<span id="cb27-18"><a href="#cb27-18" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(</span>
<span id="cb27-19"><a href="#cb27-19" aria-hidden="true" tabindex="-1"></a>    <span class="st">`</span><span class="at">Algorithm Recommendation</span><span class="st">`</span> <span class="ot">=</span> <span class="fu">case_when</span>(</span>
<span id="cb27-20"><a href="#cb27-20" aria-hidden="true" tabindex="-1"></a>    <span class="st">`</span><span class="at">Reliability Category</span><span class="st">`</span> <span class="sc">==</span> <span class="st">"High Confidence"</span> <span class="sc">~</span> <span class="st">"Safe for Algorithmic Decisions"</span>,</span>
<span id="cb27-21"><a href="#cb27-21" aria-hidden="true" tabindex="-1"></a>    <span class="st">`</span><span class="at">Reliability Category</span><span class="st">`</span> <span class="sc">==</span> <span class="st">"Moderate Confidence"</span> <span class="sc">~</span> <span class="st">"Use with caution - monitor outcomes"</span>,</span>
<span id="cb27-22"><a href="#cb27-22" aria-hidden="true" tabindex="-1"></a>    <span class="st">`</span><span class="at">Reliability Category</span><span class="st">`</span> <span class="sc">==</span> <span class="st">"Low Confidence"</span> <span class="sc">~</span> <span class="st">"Requires manual review or additional data"</span></span>
<span id="cb27-23"><a href="#cb27-23" aria-hidden="true" tabindex="-1"></a>    )</span>
<span id="cb27-24"><a href="#cb27-24" aria-hidden="true" tabindex="-1"></a>  )</span>
<span id="cb27-25"><a href="#cb27-25" aria-hidden="true" tabindex="-1"></a><span class="fu">tibble</span>(summary_overall)<span class="sc">%&gt;%</span></span>
<span id="cb27-26"><a href="#cb27-26" aria-hidden="true" tabindex="-1"></a>  <span class="fu">kable</span>(<span class="at">caption =</span> <span class="st">"County Income Data Reliability and Guide for Data Use - Algorithmic Recommendations &lt;br&gt; &lt;em&gt;For ethnic and race related analysis manual analysis and further data cleaning required"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<caption>County Income Data Reliability and Guide for Data Use - Algorithmic Recommendations <br> <em>For ethnic and race related analysis manual analysis and further data cleaning required</em></caption>
<colgroup>
<col style="width: 11%">
<col style="width: 17%">
<col style="width: 24%">
<col style="width: 15%">
<col style="width: 30%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">County</th>
<th style="text-align: right;">Median Household Income</th>
<th style="text-align: right;">Margin of Error for HH Income (%)</th>
<th style="text-align: left;">Reliability Category</th>
<th style="text-align: left;">Algorithm Recommendation</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Alameda</td>
<td style="text-align: right;">122488</td>
<td style="text-align: right;">1.0049964</td>
<td style="text-align: left;">High Confidence</td>
<td style="text-align: left;">Safe for Algorithmic Decisions</td>
</tr>
<tr class="even">
<td style="text-align: left;">Alpine</td>
<td style="text-align: right;">101125</td>
<td style="text-align: right;">17.2479604</td>
<td style="text-align: left;">Low Confidence</td>
<td style="text-align: left;">Requires manual review or additional data</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Amador</td>
<td style="text-align: right;">74853</td>
<td style="text-align: right;">8.0798365</td>
<td style="text-align: left;">Moderate Confidence</td>
<td style="text-align: left;">Use with caution - monitor outcomes</td>
</tr>
<tr class="even">
<td style="text-align: left;">Butte</td>
<td style="text-align: right;">66085</td>
<td style="text-align: right;">3.4213513</td>
<td style="text-align: left;">High Confidence</td>
<td style="text-align: left;">Safe for Algorithmic Decisions</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Calaveras</td>
<td style="text-align: right;">77526</td>
<td style="text-align: right;">4.9983231</td>
<td style="text-align: left;">High Confidence</td>
<td style="text-align: left;">Safe for Algorithmic Decisions</td>
</tr>
<tr class="even">
<td style="text-align: left;">Colusa</td>
<td style="text-align: right;">69619</td>
<td style="text-align: right;">8.2520576</td>
<td style="text-align: left;">Moderate Confidence</td>
<td style="text-align: left;">Use with caution - monitor outcomes</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Contra Costa</td>
<td style="text-align: right;">120020</td>
<td style="text-align: right;">1.2464589</td>
<td style="text-align: left;">High Confidence</td>
<td style="text-align: left;">Safe for Algorithmic Decisions</td>
</tr>
<tr class="even">
<td style="text-align: left;">Del Norte</td>
<td style="text-align: right;">61149</td>
<td style="text-align: right;">7.1562904</td>
<td style="text-align: left;">Moderate Confidence</td>
<td style="text-align: left;">Use with caution - monitor outcomes</td>
</tr>
<tr class="odd">
<td style="text-align: left;">El Dorado</td>
<td style="text-align: right;">99246</td>
<td style="text-align: right;">3.3552990</td>
<td style="text-align: left;">High Confidence</td>
<td style="text-align: left;">Safe for Algorithmic Decisions</td>
</tr>
<tr class="even">
<td style="text-align: left;">Fresno</td>
<td style="text-align: right;">67756</td>
<td style="text-align: right;">1.4271799</td>
<td style="text-align: left;">High Confidence</td>
<td style="text-align: left;">Safe for Algorithmic Decisions</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Glenn</td>
<td style="text-align: right;">64033</td>
<td style="text-align: right;">6.1889963</td>
<td style="text-align: left;">Moderate Confidence</td>
<td style="text-align: left;">Use with caution - monitor outcomes</td>
</tr>
<tr class="even">
<td style="text-align: left;">Humboldt</td>
<td style="text-align: right;">57881</td>
<td style="text-align: right;">3.6816917</td>
<td style="text-align: left;">High Confidence</td>
<td style="text-align: left;">Safe for Algorithmic Decisions</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Imperial</td>
<td style="text-align: right;">53847</td>
<td style="text-align: right;">4.1116497</td>
<td style="text-align: left;">High Confidence</td>
<td style="text-align: left;">Safe for Algorithmic Decisions</td>
</tr>
<tr class="even">
<td style="text-align: left;">Inyo</td>
<td style="text-align: right;">63417</td>
<td style="text-align: right;">8.5986407</td>
<td style="text-align: left;">Moderate Confidence</td>
<td style="text-align: left;">Use with caution - monitor outcomes</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Kern</td>
<td style="text-align: right;">63883</td>
<td style="text-align: right;">2.0741042</td>
<td style="text-align: left;">High Confidence</td>
<td style="text-align: left;">Safe for Algorithmic Decisions</td>
</tr>
<tr class="even">
<td style="text-align: left;">Kings</td>
<td style="text-align: right;">68540</td>
<td style="text-align: right;">3.2871316</td>
<td style="text-align: left;">High Confidence</td>
<td style="text-align: left;">Safe for Algorithmic Decisions</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Lake</td>
<td style="text-align: right;">56259</td>
<td style="text-align: right;">4.3353064</td>
<td style="text-align: left;">High Confidence</td>
<td style="text-align: left;">Safe for Algorithmic Decisions</td>
</tr>
<tr class="even">
<td style="text-align: left;">Lassen</td>
<td style="text-align: right;">59515</td>
<td style="text-align: right;">5.9665631</td>
<td style="text-align: left;">Moderate Confidence</td>
<td style="text-align: left;">Use with caution - monitor outcomes</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Los Angeles</td>
<td style="text-align: right;">83411</td>
<td style="text-align: right;">0.5263095</td>
<td style="text-align: left;">High Confidence</td>
<td style="text-align: left;">Safe for Algorithmic Decisions</td>
</tr>
<tr class="even">
<td style="text-align: left;">Madera</td>
<td style="text-align: right;">73543</td>
<td style="text-align: right;">3.8671254</td>
<td style="text-align: left;">High Confidence</td>
<td style="text-align: left;">Safe for Algorithmic Decisions</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Marin</td>
<td style="text-align: right;">142019</td>
<td style="text-align: right;">2.8855294</td>
<td style="text-align: left;">High Confidence</td>
<td style="text-align: left;">Safe for Algorithmic Decisions</td>
</tr>
<tr class="even">
<td style="text-align: left;">Mariposa</td>
<td style="text-align: right;">60021</td>
<td style="text-align: right;">8.8185802</td>
<td style="text-align: left;">Moderate Confidence</td>
<td style="text-align: left;">Use with caution - monitor outcomes</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Mendocino</td>
<td style="text-align: right;">61335</td>
<td style="text-align: right;">3.5835983</td>
<td style="text-align: left;">High Confidence</td>
<td style="text-align: left;">Safe for Algorithmic Decisions</td>
</tr>
<tr class="even">
<td style="text-align: left;">Merced</td>
<td style="text-align: right;">64772</td>
<td style="text-align: right;">3.3069845</td>
<td style="text-align: left;">High Confidence</td>
<td style="text-align: left;">Safe for Algorithmic Decisions</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Modoc</td>
<td style="text-align: right;">54962</td>
<td style="text-align: right;">9.8049562</td>
<td style="text-align: left;">Moderate Confidence</td>
<td style="text-align: left;">Use with caution - monitor outcomes</td>
</tr>
<tr class="even">
<td style="text-align: left;">Mono</td>
<td style="text-align: right;">82038</td>
<td style="text-align: right;">18.7571613</td>
<td style="text-align: left;">Low Confidence</td>
<td style="text-align: left;">Requires manual review or additional data</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Monterey</td>
<td style="text-align: right;">91043</td>
<td style="text-align: right;">2.0869260</td>
<td style="text-align: left;">High Confidence</td>
<td style="text-align: left;">Safe for Algorithmic Decisions</td>
</tr>
<tr class="even">
<td style="text-align: left;">Napa</td>
<td style="text-align: right;">105809</td>
<td style="text-align: right;">2.8173407</td>
<td style="text-align: left;">High Confidence</td>
<td style="text-align: left;">Safe for Algorithmic Decisions</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Nevada</td>
<td style="text-align: right;">79395</td>
<td style="text-align: right;">4.8151647</td>
<td style="text-align: left;">High Confidence</td>
<td style="text-align: left;">Safe for Algorithmic Decisions</td>
</tr>
<tr class="even">
<td style="text-align: left;">Orange</td>
<td style="text-align: right;">109361</td>
<td style="text-align: right;">0.8065032</td>
<td style="text-align: left;">High Confidence</td>
<td style="text-align: left;">Safe for Algorithmic Decisions</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Placer</td>
<td style="text-align: right;">109375</td>
<td style="text-align: right;">1.6969143</td>
<td style="text-align: left;">High Confidence</td>
<td style="text-align: left;">Safe for Algorithmic Decisions</td>
</tr>
<tr class="even">
<td style="text-align: left;">Plumas</td>
<td style="text-align: right;">67885</td>
<td style="text-align: right;">11.4487737</td>
<td style="text-align: left;">Low Confidence</td>
<td style="text-align: left;">Requires manual review or additional data</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Riverside</td>
<td style="text-align: right;">84505</td>
<td style="text-align: right;">1.2555470</td>
<td style="text-align: left;">High Confidence</td>
<td style="text-align: left;">Safe for Algorithmic Decisions</td>
</tr>
<tr class="even">
<td style="text-align: left;">Sacramento</td>
<td style="text-align: right;">84010</td>
<td style="text-align: right;">0.9713129</td>
<td style="text-align: left;">High Confidence</td>
<td style="text-align: left;">Safe for Algorithmic Decisions</td>
</tr>
<tr class="odd">
<td style="text-align: left;">San Benito</td>
<td style="text-align: right;">104451</td>
<td style="text-align: right;">5.2282889</td>
<td style="text-align: left;">Moderate Confidence</td>
<td style="text-align: left;">Use with caution - monitor outcomes</td>
</tr>
<tr class="even">
<td style="text-align: left;">San Bernardino</td>
<td style="text-align: right;">77423</td>
<td style="text-align: right;">1.0410343</td>
<td style="text-align: left;">High Confidence</td>
<td style="text-align: left;">Safe for Algorithmic Decisions</td>
</tr>
<tr class="odd">
<td style="text-align: left;">San Diego</td>
<td style="text-align: right;">96974</td>
<td style="text-align: right;">1.0239858</td>
<td style="text-align: left;">High Confidence</td>
<td style="text-align: left;">Safe for Algorithmic Decisions</td>
</tr>
<tr class="even">
<td style="text-align: left;">San Francisco</td>
<td style="text-align: right;">136689</td>
<td style="text-align: right;">1.4295225</td>
<td style="text-align: left;">High Confidence</td>
<td style="text-align: left;">Safe for Algorithmic Decisions</td>
</tr>
<tr class="odd">
<td style="text-align: left;">San Joaquin</td>
<td style="text-align: right;">82837</td>
<td style="text-align: right;">1.7480112</td>
<td style="text-align: left;">High Confidence</td>
<td style="text-align: left;">Safe for Algorithmic Decisions</td>
</tr>
<tr class="even">
<td style="text-align: left;">San Luis Obispo</td>
<td style="text-align: right;">90158</td>
<td style="text-align: right;">2.5632778</td>
<td style="text-align: left;">High Confidence</td>
<td style="text-align: left;">Safe for Algorithmic Decisions</td>
</tr>
<tr class="odd">
<td style="text-align: left;">San Mateo</td>
<td style="text-align: right;">149907</td>
<td style="text-align: right;">1.7484174</td>
<td style="text-align: left;">High Confidence</td>
<td style="text-align: left;">Safe for Algorithmic Decisions</td>
</tr>
<tr class="even">
<td style="text-align: left;">Santa Barbara</td>
<td style="text-align: right;">92332</td>
<td style="text-align: right;">2.0458779</td>
<td style="text-align: left;">High Confidence</td>
<td style="text-align: left;">Safe for Algorithmic Decisions</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Santa Clara</td>
<td style="text-align: right;">153792</td>
<td style="text-align: right;">1.0046036</td>
<td style="text-align: left;">High Confidence</td>
<td style="text-align: left;">Safe for Algorithmic Decisions</td>
</tr>
<tr class="even">
<td style="text-align: left;">Santa Cruz</td>
<td style="text-align: right;">104409</td>
<td style="text-align: right;">3.0390100</td>
<td style="text-align: left;">High Confidence</td>
<td style="text-align: left;">Safe for Algorithmic Decisions</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Shasta</td>
<td style="text-align: right;">68347</td>
<td style="text-align: right;">3.6285426</td>
<td style="text-align: left;">High Confidence</td>
<td style="text-align: left;">Safe for Algorithmic Decisions</td>
</tr>
<tr class="even">
<td style="text-align: left;">Sierra</td>
<td style="text-align: right;">61108</td>
<td style="text-align: right;">15.1158604</td>
<td style="text-align: left;">Low Confidence</td>
<td style="text-align: left;">Requires manual review or additional data</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Siskiyou</td>
<td style="text-align: right;">53898</td>
<td style="text-align: right;">4.8981409</td>
<td style="text-align: left;">High Confidence</td>
<td style="text-align: left;">Safe for Algorithmic Decisions</td>
</tr>
<tr class="even">
<td style="text-align: left;">Solano</td>
<td style="text-align: right;">97037</td>
<td style="text-align: right;">1.7766419</td>
<td style="text-align: left;">High Confidence</td>
<td style="text-align: left;">Safe for Algorithmic Decisions</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Sonoma</td>
<td style="text-align: right;">99266</td>
<td style="text-align: right;">2.0026998</td>
<td style="text-align: left;">High Confidence</td>
<td style="text-align: left;">Safe for Algorithmic Decisions</td>
</tr>
<tr class="even">
<td style="text-align: left;">Stanislaus</td>
<td style="text-align: right;">74872</td>
<td style="text-align: right;">1.8311251</td>
<td style="text-align: left;">High Confidence</td>
<td style="text-align: left;">Safe for Algorithmic Decisions</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Sutter</td>
<td style="text-align: right;">72654</td>
<td style="text-align: right;">4.7141245</td>
<td style="text-align: left;">High Confidence</td>
<td style="text-align: left;">Safe for Algorithmic Decisions</td>
</tr>
<tr class="even">
<td style="text-align: left;">Tehama</td>
<td style="text-align: right;">59029</td>
<td style="text-align: right;">6.9508208</td>
<td style="text-align: left;">Moderate Confidence</td>
<td style="text-align: left;">Use with caution - monitor outcomes</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Trinity</td>
<td style="text-align: right;">47317</td>
<td style="text-align: right;">12.4479574</td>
<td style="text-align: left;">Low Confidence</td>
<td style="text-align: left;">Requires manual review or additional data</td>
</tr>
<tr class="even">
<td style="text-align: left;">Tulare</td>
<td style="text-align: right;">64474</td>
<td style="text-align: right;">2.3094581</td>
<td style="text-align: left;">High Confidence</td>
<td style="text-align: left;">Safe for Algorithmic Decisions</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Tuolumne</td>
<td style="text-align: right;">70432</td>
<td style="text-align: right;">6.6603249</td>
<td style="text-align: left;">Moderate Confidence</td>
<td style="text-align: left;">Use with caution - monitor outcomes</td>
</tr>
<tr class="even">
<td style="text-align: left;">Ventura</td>
<td style="text-align: right;">102141</td>
<td style="text-align: right;">1.4959713</td>
<td style="text-align: left;">High Confidence</td>
<td style="text-align: left;">Safe for Algorithmic Decisions</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Yolo</td>
<td style="text-align: right;">85097</td>
<td style="text-align: right;">2.7415773</td>
<td style="text-align: left;">High Confidence</td>
<td style="text-align: left;">Safe for Algorithmic Decisions</td>
</tr>
<tr class="even">
<td style="text-align: left;">Yuba</td>
<td style="text-align: right;">66693</td>
<td style="text-align: right;">4.1923440</td>
<td style="text-align: left;">High Confidence</td>
<td style="text-align: left;">Safe for Algorithmic Decisions</td>
</tr>
</tbody>
</table>
</div>
</div>
<p><strong>Key Recommendations:</strong></p>
<p><strong>Your Task:</strong> Use your analysis results to provide specific guidance to the department.</p>
<ol type="1">
<li><strong>Counties suitable for immediate algorithmic implementation:</strong> Alameda; Butte; Calaveras; Contra Costa; El Dorado; Fresno; Humboldt; Imperial; Kern; Kings; Lake; Los Angeles; Madera; Marin; Mendocino; Merced; Monterey; Napa; Nevada; Orange; Placer; Riverside; Sacramento; San Bernardino; San Diego; San Francisco; San Joaquin; San Luis Obispo; San Mateo; Santa Barbara; Santa Clara; Santa Cruz; Shasta; Siskiyou; Solano; Sonoma; Stanislaus; Sutter; Tulare; Ventura; Yolo; Yuba.</li>
</ol>
<ul>
<li>These are high reliability for income with margin of error below 5%.</li>
</ul>
<ol start="2" type="1">
<li><strong>Counties requiring additional oversight:</strong> Amador; Colusa; Del Norte; Glenn; Inyo; Lassen; Mariposa; Modoc; San Benito; Tehama; Tuolumne.</li>
</ol>
<ul>
<li>Frequent audits for analysis required, intervention in terms of surveying residents for the outcomes from decisions made by the planning department.</li>
</ul>
<ol start="3" type="1">
<li><strong>Counties needing alternative approaches:</strong> Alpine; Mono; Plumas; Sierra; Trinity. -Manual review of data- rezoning considerations (redrawing boundaries), frequent surveying and more direct community level engagement required.</li>
</ol>
</section>
<section id="questions-for-further-investigation" class="level2">
<h2 class="anchored" data-anchor-id="questions-for-further-investigation">Questions for Further Investigation</h2>
<ol type="1">
<li>Are high margins of error clustered in specific types of places, such as rural or low-population areas, rather than being randomly distributed across counties and census tracts?</li>
<li>Is it possible to analyze the spatial patterns and see if rezoning of census tracts is possible for added data reliability.</li>
</ol>
</section>
</section>
<section id="technical-notes" class="level1">
<h1>Technical Notes</h1>
<p><strong>Data Sources:</strong> - U.S. Census Bureau, American Community Survey 2018-2022 5-Year Estimates - Retrieved via tidycensus R package on 07-09 February 2026</p>
<p><strong>Reproducibility:</strong> - All analysis conducted in R - Census API key required for replication - Complete code and documentation available at: https://ssatyal-ux.github.io/shubhanga_satyal_CPLN_20Jan2026/</p>
<p><strong>Methodology Notes:</strong> While selecting my counties, I initially attempted to use slice_sample() to randomize the selection. However, to ensure consistency in the data and to avoid issues when referring to the same counties for census tract–level analysis, I used slice() instead.</p>
<p>I used help from the class exercise and additional support from ChatGPT for explanations on how to write code when I was stuck. I also used the dplyr cheatsheet for reference.</p>
<p><strong>Limitations:</strong> All census tracts in my selected counties were unrelable for ethnicity and race data. Thus not allowing further investigation.</p>
<hr>
<section id="submission-checklist" class="level2">
<h2 class="anchored" data-anchor-id="submission-checklist">Submission Checklist</h2>
<p>Before submitting your portfolio link on Canvas:</p>
<ul class="task-list">
<li><label><input type="checkbox" checked="">All code chunks run without errors</label></li>
<li><label><input type="checkbox" checked="">All “[Fill this in]” prompts have been completed</label></li>
<li><label><input type="checkbox" checked="">Tables are properly formatted and readable</label></li>
<li><label><input type="checkbox" checked="">Executive summary addresses all four required components</label></li>
<li><label><input type="checkbox" checked="">Portfolio navigation includes this assignment</label></li>
<li><label><input type="checkbox" checked="">Census API key is properly set</label></li>
<li><label><input type="checkbox" checked="">Document renders correctly to HTML</label></li>
</ul>
<p><strong>Remember:</strong> Submit your portfolio URL on Canvas, not the file itself. Your assignment should be accessible at <code>your-portfolio-url/labs/lab_1/your_file_name.html</code></p>


</section>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
</div> <!-- /content -->




</body></html>